# MLHUB — production image (Laravel 13, PHP 8.3, Apache).
# Biến môi trường thật (DB, Redis, APP_KEY, mail, license…) chỉ cấu hình trên Coolify — KHÔNG ghi secret vào Dockerfile.

# -----------------------------------------------------------------------------
# Stage 1: Composer dependencies (cached layer on composer.json / composer.lock)
# -----------------------------------------------------------------------------
FROM composer:2 AS build
ARG APP_NAME=MLHUB
ARG MLHUB_SYNC_ENV_OPTIONS=true
ARG APP_KEY=base64:ZsLIT5SiyQFlitofPwZS+/qfEjyOIVDwYOiZXHPrcIA=
ARG APP_ENV=production
ARG APP_INSTALLED=true
ARG MLHUB_NO_PLAN_ACCESS_LABEL=Free
ARG APP_URL=https://mlhub.vn
ARG APP_DEBUG=false
ARG MLHUB_NO_PLAN_CREDITS_LIMIT=100
ARG MLHUB_NO_PLAN_ACCESS_ENABLED=true
ARG MLHUB_SYSTEM_CRON_SECURE_KEY=
ARG MLHUB_NO_PLAN_MAX_CAMPAIGNS=5
ARG LOG_CHANNEL=stack
ARG MAIL_EHLO_DOMAIN=mlhub.vn
ARG APP_LOCALE=vi
ARG MLHUB_CONTACT_WEBSITE=https://mlhub.vn
ARG APP_FALLBACK_LOCALE=vi
ARG MLHUB_NO_PLAN_MAX_BUSINESSES=1
ARG APP_FAKER_LOCALE=vi_VN
ARG APP_MAINTENANCE_DRIVER=file
ARG BCRYPT_ROUNDS=12
ARG LOG_STACK=single
ARG THEME_FRONTEND=mlhubfrontend
ARG LOG_LEVEL=error
ARG DB_HOST=vdd0voqmyudditvwfhuscrta
ARG AWS_ENDPOINT=
ARG AWS_URL=
ARG DB_CONNECTION=mysql
ARG LOG_DEPRECATIONS_CHANNEL=null
ARG THEME_BACKEND=mlhubbackend
ARG DB_DATABASE=default
ARG DB_PORT=3306
ARG SESSION_ENCRYPT=false
ARG SESSION_PATH=/
ARG GOOGLE_BUSINESS_CLIENT_ID=266306087862-6cq30ofj92o1tg1809246bi1rh4edmm9.apps.googleusercontent.com
ARG DB_USERNAME=mysql
ARG GOOGLE_BUSINESS_CLIENT_SECRET=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
ARG SESSION_LIFETIME=120
ARG SESSION_DRIVER=redis
ARG MLHUB_NO_PLAN_MAX_LANDING_PAGES=5
ARG DB_PASSWORD=FXlAITZo3hgZYZJ26pdHSn7e70Zm6EAh0uUTgNfUJgEScn6x24YiwAe9x89gmgIo
ARG MLHUB_NO_PLAN_MAX_QR_CODES=15
ARG SESSION_SECURE_COOKIE=true
ARG MLHUB_NO_PLAN_MAX_TEMPLATES=5
ARG MLHUB_NO_PLAN_MAX_STORAGE_MB=512
ARG SESSION_DOMAIN=.mlhub.vn
ARG CACHE_STORE=redis
ARG MLHUB_CAPTCHA_TYPE=turnstile
ARG TRUSTED_PROXIES=*
ARG LIVEWIRE_RELEASE_TOKEN=20260611
ARG SESSION_COOKIE=mlhub_session
ARG MEMCACHED_HOST=127.0.0.1
ARG BROADCAST_CONNECTION=log
ARG FILESYSTEM_DISK=public
ARG QUEUE_CONNECTION=redis
ARG REDIS_CLIENT=phpredis
ARG REDIS_HOST=w13teqa9fusj56ddpl8w8ezf
ARG MLHUB_CLOUDFLARE_TURNSTILE_SITE_KEY=0x4AAAAAADYVJ5pkiNy7poMX
ARG MLHUB_CONTACT_WORKING_HOURS=Thứ 2 - Thứ 6: 09:00 - 18:00
ARG REDIS_PORT=6379
ARG MLHUB_ADMIN_PLAN_SLUG=agency-lifetime
ARG MAIL_PORT=587
ARG MLHUB_LICENSE_PURCHASE_CODE=d80177d1-4974-4e46-a7f3-564da3bc83f7
ARG MLHUB_ALLOW_RESET_DEMO=true
ARG MAIL_MAILER=smtp
ARG MAIL_FROM_NAME=${APP_NAME}
ARG MAIL_SCHEME=tls
ARG MAIL_USERNAME=emailit
ARG MAIL_HOST=smtp.emailit.com
ARG MLHUB_GOOGLE_RECAPTCHA_SITE_KEY=6LeeAAItAAAAABtl-viskX16U6_QbyjCXrz2v6HG
ARG MLHUB_LICENSE_DOMAIN=mlhub.vn
ARG MLHUB_CLOUDFLARE_TURNSTILE_SECRET_KEY=0x4AAAAAADYVJw4b7xm2WC3UNugtP1miHzw
ARG MLHUB_CONTACT_EMAIL=admin@mlhub.vn
ARG MAIL_PASSWORD=secret_LHzlnBLwXz8ZGV0JztVkvn9mf4VFKE14
ARG REDIS_PASSWORD=VJj4BYh0Oedesmer0LWeyeN8tfSQKuwBos9JfHamP375e9rAxYoWk40R4HLWPGlh
ARG MAIL_FROM_ADDRESS=noreply@mlhub.vn
ARG WASABI_URL=
ARG VITE_APP_NAME=${APP_NAME}
ARG SITE_TITLE=MLHUB
ARG AWS_USE_PATH_STYLE_ENDPOINT=false
ARG SITE_DESCRIPTION=Nền tảng Marketing Automation hỗ trợ tăng đánh giá, đặt lịch, mã ưu đãi, phản hồi & tạo khách hàng tiềm năng.
ARG WASABI_ACCESS_KEY_ID=
ARG APP_TIMEZONE=Asia/Ho_Chi_Minh
ARG MLHUB_GOOGLE_RECAPTCHA_SECRET_KEY=6LeeAAItAAAAAM6gBf1GGNsO6wSA8OteZTG3ZHXV
ARG AWS_ACCESS_KEY_ID=
ARG MLHUB_GOOGLE_ANALYTICS_STATUS=1
ARG AWS_SECRET_ACCESS_KEY=
ARG WASABI_SECRET_ACCESS_KEY=
ARG WASABI_DEFAULT_REGION=us-east-1
ARG WASABI_BUCKET=
ARG AWS_DEFAULT_REGION=us-east-1
ARG AWS_BUCKET=
ARG MLHUB_LICENSE_VERSION=1.0.1
ARG MLHUB_LICENSE_INSTALL_PATH=./
ARG MLHUB_GOOGLE_ANALYTICS_TRACK_GUEST=1
ARG MLHUB_FIRST_USER_EMAIL=admin@mlhub.vn
ARG SITE_KEYWORDS=MLHUB, Marketing Automation, đánh giá, đặt lịch, mã ưu đãi, phản hồi, khách hàng tiềm năng, hộ kinh doanh
ARG MLHUB_FIRST_USER_USERNAME=mlhubadmin
ARG MLHUB_FIRST_USER_PASSWORD=98Fb1288@@dvk192
ARG MLHUB_GOOGLE_ANALYTICS_MEASUREMENT_ID=G-ZY1P6YJLME
ARG MLHUB_LICENSE_TYPE=Extended License
ARG MLHUB_STARTING_ID=147123468
ARG MLHUB_FIRST_USER_NAME=MLHUB Admin
ARG RUN_QUEUE_WORKER=true
ARG APP_DEMO=false
ARG MLHUB_FIRST_USER_LOCALE=vi
ARG MLHUB_LICENSE_PRODUCT_ID=10252026
ARG MLHUB_NO_PLAN_CREDITS_USAGE=true
ARG STRIPE_PUBLISHABLE_KEY=
ARG MLHUB_NO_PLAN_FILE_GOOGLE_DRIVE=true
ARG MLHUB_NO_PLAN_LOCALBOOST=true
ARG WASABI_ENDPOINT=
ARG STRIPE_SECRET_KEY=
ARG MLHUB_NO_PLAN_REMOVE_BRANDING=false
ARG WASABI_USE_PATH_STYLE_ENDPOINT=false
ARG MLHUB_NO_PLAN_FILES=true
ARG MLHUB_NO_PLAN_MAX_FILE_SIZE_MB=32
ARG MLHUB_GOOGLE_ANALYTICS_TRACK_APP=1
ARG MLHUB_NO_PLAN_IMAGE_EDITOR=true
ARG STRIPE_STATUS=0
ARG MLHUB_NO_PLAN_SEARCH_MEDIA_ONLINE=true
ARG MLHUB_NO_PLAN_FILE_DROPBOX=true
ARG MLHUB_NO_PLAN_FILE_ONEDRIVE=true
ARG MLHUB_NO_PLAN_SUPPORT=true
ARG MLHUB_NO_PLAN_AFFILIATE=true
ARG MLHUB_GOOGLE_RECAPTCHA_STATUS=0
ARG MLHUB_NO_PLAN_AI_STUDIO=true
ARG MLHUB_NO_PLAN_AI_CAPTION=true
ARG MLHUB_GOOGLE_BUSINESS_STATUS=1
ARG MLHUB_NO_PLAN_AI_CONTENT_PLANNER=true
ARG MLHUB_CONTACT_PHONE=0899789225
ARG MLHUB_CONTACT_LOCATION=01 Nguyễn Văn Linh, Đà Nẵng
ARG MLHUB_NO_PLAN_AI_REPURPOSE=true
ARG STRIPE_WEBHOOK_SECRET=
ARG MLHUB_NO_PLAN_AI_IMAGE=true
ARG MLHUB_NO_PLAN_TEAMS=true
ARG MLHUB_NO_PLAN_MAX_TEAM_MEMBERS=2
ARG MLHUB_NO_PLAN_ADVANCED_CRM=true
ARG MLHUB_NO_PLAN_GOOGLE_LOCATIONS=1
ARG MLHUB_AUTH_LANDING_PAGE_STATUS=1
ARG MLHUB_NO_PLAN_CRM_TAGS=10
ARG MLHUB_AUTH_USER_CHANGE_EMAIL_STATUS=0
ARG MLHUB_NO_PLAN_CRM_SEGMENTS=3
ARG MLHUB_AUTH_SIGNUP_PAGE_STATUS=1
ARG MLHUB_NO_PLAN_CRM_TASKS=20
ARG MLHUB_NO_PLAN_CRM_AUTOMATIONS=2
ARG MLHUB_AUTH_ACTIVATION_EMAIL_STATUS=1
ARG MLHUB_NO_PLAN_CRM_RETENTION_DAYS=90
ARG MLHUB_NO_PLAN_GOOGLE_BUSINESS=true
ARG MLHUB_AUTH_WELCOME_EMAIL_STATUS=1
ARG MLHUB_NO_PLAN_GOOGLE_CONNECTIONS=1
ARG MLHUB_NO_PLAN_GOOGLE_REVIEW_SYNC=true
ARG MLHUB_NO_PLAN_GOOGLE_REVIEW_REPLY=true
ARG MLHUB_NO_PLAN_EMAIL_CONDITIONS=true
ARG MLHUB_NO_PLAN_GOOGLE_INSIGHTS=true
ARG MLHUB_AUTH_TWO_FACTOR_STATUS=1
ARG MLHUB_AUTH_GOOGLE_LOGIN_STATUS=1
ARG MLHUB_NO_PLAN_GOOGLE_POSTS=true
ARG MLHUB_NO_PLAN_EMAIL_AUTOMATION=true
ARG MLHUB_AUTH_GOOGLE_LOGIN_CLIENT_ID=266306087862-0cf2mkerddr0dic2fgj1j25jpb269gg2.apps.googleusercontent.com
ARG MLHUB_NO_PLAN_MAX_EMAIL_AUTOMATIONS=2
ARG MLHUB_NO_PLAN_MAX_EMAIL_TEMPLATES=3
ARG MLHUB_NO_PLAN_EMAILS_PER_MONTH=200
ARG MLHUB_NO_PLAN_EMAIL_DELAY=true
ARG MLHUB_AUTH_USER_CHANGE_USERNAME_STATUS=0
ARG MLHUB_NO_PLAN_WHATSAPP=true
ARG MLHUB_NO_PLAN_MAX_WHATSAPP_RULES=2
ARG MLHUB_NO_PLAN_WEBHOOK_HEADERS=true
ARG MLHUB_NO_PLAN_MAX_WHATSAPP_TEMPLATES=2
ARG MLHUB_AUTH_GOOGLE_LOGIN_CLIENT_SECRET=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
ARG MLHUB_NO_PLAN_WHATSAPP_MESSAGES_PER_MONTH=50
ARG MLHUB_NO_PLAN_WHATSAPP_CLOUD_API=true
ARG MLHUB_AUTH_FACEBOOK_LOGIN_STATUS=0
ARG MLHUB_NO_PLAN_WHATSAPP_TEMPLATE_MSG=true
ARG MLHUB_NO_PLAN_WEBHOOK=true
ARG MLHUB_AUTH_FACEBOOK_LOGIN_APP_ID=
ARG MLHUB_NO_PLAN_MAX_WEBHOOK_RULES=2
ARG MLHUB_NO_PLAN_WEBHOOKS_PER_MONTH=300
ARG MLHUB_AUTH_FACEBOOK_LOGIN_APP_SECRET=
ARG MLHUB_NO_PLAN_MAX_LOYALTY_CARDS=1
ARG MLHUB_AUTH_FACEBOOK_LOGIN_APP_VERSION=v22.0
ARG MLHUB_NO_PLAN_MAX_LOYALTY_CUSTOMERS=100
ARG MLHUB_NO_PLAN_MAX_REFERRAL_CAMPAIGNS=1
ARG MLHUB_NO_PLAN_LOYALTY_REWARDS=true
ARG MLHUB_NO_PLAN_LOYALTY_STAFF_REDEEM=true
ARG MLHUB_AUTH_X_LOGIN_STATUS=0
ARG MLHUB_NO_PLAN_CUSTOM_DOMAINS=true
ARG MLHUB_NO_PLAN_MAX_CUSTOM_DOMAINS=1
ARG MLHUB_AUTH_X_LOGIN_CLIENT_ID=
ARG MLHUB_AUTH_X_LOGIN_CLIENT_SECRET=
ARG MLHUB_CLOUDFLARE_TURNSTILE_STATUS=1
ARG MLHUB_NO_PLAN_WEBHOOK_RETRY=true
ARG MLHUB_NO_PLAN_LOYALTY=true
ARG COOLIFY_URL=https://mlhub.vn,https//www.mlhub.vn
ARG COOLIFY_FQDN=mlhub.vn,https
ARG COOLIFY_BRANCH='main'
ARG COOLIFY_RESOURCE_UUID=mggu45o8q8aso8stbepn622j

WORKDIR /app

COPY composer.json composer.lock ./

RUN composer install \
    --no-dev \
    --optimize-autoloader \
    --no-scripts \
    --no-interaction \
    --prefer-dist

# -----------------------------------------------------------------------------
# Stage 2: Production runtime (Apache + PHP 8.3)
# -----------------------------------------------------------------------------
FROM php:8.3-apache-bookworm AS production
ARG APP_NAME=MLHUB
ARG MLHUB_SYNC_ENV_OPTIONS=true
ARG APP_KEY=base64:ZsLIT5SiyQFlitofPwZS+/qfEjyOIVDwYOiZXHPrcIA=
ARG APP_ENV=production
ARG APP_INSTALLED=true
ARG MLHUB_NO_PLAN_ACCESS_LABEL=Free
ARG APP_URL=https://mlhub.vn
ARG APP_DEBUG=false
ARG MLHUB_NO_PLAN_CREDITS_LIMIT=100
ARG MLHUB_NO_PLAN_ACCESS_ENABLED=true
ARG MLHUB_SYSTEM_CRON_SECURE_KEY=
ARG MLHUB_NO_PLAN_MAX_CAMPAIGNS=5
ARG LOG_CHANNEL=stack
ARG MAIL_EHLO_DOMAIN=mlhub.vn
ARG APP_LOCALE=vi
ARG MLHUB_CONTACT_WEBSITE=https://mlhub.vn
ARG APP_FALLBACK_LOCALE=vi
ARG MLHUB_NO_PLAN_MAX_BUSINESSES=1
ARG APP_FAKER_LOCALE=vi_VN
ARG APP_MAINTENANCE_DRIVER=file
ARG BCRYPT_ROUNDS=12
ARG LOG_STACK=single
ARG THEME_FRONTEND=mlhubfrontend
ARG LOG_LEVEL=error
ARG DB_HOST=vdd0voqmyudditvwfhuscrta
ARG AWS_ENDPOINT=
ARG AWS_URL=
ARG DB_CONNECTION=mysql
ARG LOG_DEPRECATIONS_CHANNEL=null
ARG THEME_BACKEND=mlhubbackend
ARG DB_DATABASE=default
ARG DB_PORT=3306
ARG SESSION_ENCRYPT=false
ARG SESSION_PATH=/
ARG GOOGLE_BUSINESS_CLIENT_ID=266306087862-6cq30ofj92o1tg1809246bi1rh4edmm9.apps.googleusercontent.com
ARG DB_USERNAME=mysql
ARG GOOGLE_BUSINESS_CLIENT_SECRET=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
ARG SESSION_LIFETIME=120
ARG SESSION_DRIVER=redis
ARG MLHUB_NO_PLAN_MAX_LANDING_PAGES=5
ARG DB_PASSWORD=FXlAITZo3hgZYZJ26pdHSn7e70Zm6EAh0uUTgNfUJgEScn6x24YiwAe9x89gmgIo
ARG MLHUB_NO_PLAN_MAX_QR_CODES=15
ARG SESSION_SECURE_COOKIE=true
ARG MLHUB_NO_PLAN_MAX_TEMPLATES=5
ARG MLHUB_NO_PLAN_MAX_STORAGE_MB=512
ARG SESSION_DOMAIN=.mlhub.vn
ARG CACHE_STORE=redis
ARG MLHUB_CAPTCHA_TYPE=turnstile
ARG TRUSTED_PROXIES=*
ARG LIVEWIRE_RELEASE_TOKEN=20260611
ARG SESSION_COOKIE=mlhub_session
ARG MEMCACHED_HOST=127.0.0.1
ARG BROADCAST_CONNECTION=log
ARG FILESYSTEM_DISK=public
ARG QUEUE_CONNECTION=redis
ARG REDIS_CLIENT=phpredis
ARG REDIS_HOST=w13teqa9fusj56ddpl8w8ezf
ARG MLHUB_CLOUDFLARE_TURNSTILE_SITE_KEY=0x4AAAAAADYVJ5pkiNy7poMX
ARG MLHUB_CONTACT_WORKING_HOURS=Thứ 2 - Thứ 6: 09:00 - 18:00
ARG REDIS_PORT=6379
ARG MLHUB_ADMIN_PLAN_SLUG=agency-lifetime
ARG MAIL_PORT=587
ARG MLHUB_LICENSE_PURCHASE_CODE=d80177d1-4974-4e46-a7f3-564da3bc83f7
ARG MLHUB_ALLOW_RESET_DEMO=true
ARG MAIL_MAILER=smtp
ARG MAIL_FROM_NAME=${APP_NAME}
ARG MAIL_SCHEME=tls
ARG MAIL_USERNAME=emailit
ARG MAIL_HOST=smtp.emailit.com
ARG MLHUB_GOOGLE_RECAPTCHA_SITE_KEY=6LeeAAItAAAAABtl-viskX16U6_QbyjCXrz2v6HG
ARG MLHUB_LICENSE_DOMAIN=mlhub.vn
ARG MLHUB_CLOUDFLARE_TURNSTILE_SECRET_KEY=0x4AAAAAADYVJw4b7xm2WC3UNugtP1miHzw
ARG MLHUB_CONTACT_EMAIL=admin@mlhub.vn
ARG MAIL_PASSWORD=secret_LHzlnBLwXz8ZGV0JztVkvn9mf4VFKE14
ARG REDIS_PASSWORD=VJj4BYh0Oedesmer0LWeyeN8tfSQKuwBos9JfHamP375e9rAxYoWk40R4HLWPGlh
ARG MAIL_FROM_ADDRESS=noreply@mlhub.vn
ARG WASABI_URL=
ARG VITE_APP_NAME=${APP_NAME}
ARG SITE_TITLE=MLHUB
ARG AWS_USE_PATH_STYLE_ENDPOINT=false
ARG SITE_DESCRIPTION=Nền tảng Marketing Automation hỗ trợ tăng đánh giá, đặt lịch, mã ưu đãi, phản hồi & tạo khách hàng tiềm năng.
ARG WASABI_ACCESS_KEY_ID=
ARG APP_TIMEZONE=Asia/Ho_Chi_Minh
ARG MLHUB_GOOGLE_RECAPTCHA_SECRET_KEY=6LeeAAItAAAAAM6gBf1GGNsO6wSA8OteZTG3ZHXV
ARG AWS_ACCESS_KEY_ID=
ARG MLHUB_GOOGLE_ANALYTICS_STATUS=1
ARG AWS_SECRET_ACCESS_KEY=
ARG WASABI_SECRET_ACCESS_KEY=
ARG WASABI_DEFAULT_REGION=us-east-1
ARG WASABI_BUCKET=
ARG AWS_DEFAULT_REGION=us-east-1
ARG AWS_BUCKET=
ARG MLHUB_LICENSE_VERSION=1.0.1
ARG MLHUB_LICENSE_INSTALL_PATH=./
ARG MLHUB_GOOGLE_ANALYTICS_TRACK_GUEST=1
ARG MLHUB_FIRST_USER_EMAIL=admin@mlhub.vn
ARG SITE_KEYWORDS=MLHUB, Marketing Automation, đánh giá, đặt lịch, mã ưu đãi, phản hồi, khách hàng tiềm năng, hộ kinh doanh
ARG MLHUB_FIRST_USER_USERNAME=mlhubadmin
ARG MLHUB_FIRST_USER_PASSWORD=98Fb1288@@dvk192
ARG MLHUB_GOOGLE_ANALYTICS_MEASUREMENT_ID=G-ZY1P6YJLME
ARG MLHUB_LICENSE_TYPE=Extended License
ARG MLHUB_STARTING_ID=147123468
ARG MLHUB_FIRST_USER_NAME=MLHUB Admin
ARG RUN_QUEUE_WORKER=true
ARG APP_DEMO=false
ARG MLHUB_FIRST_USER_LOCALE=vi
ARG MLHUB_LICENSE_PRODUCT_ID=10252026
ARG MLHUB_NO_PLAN_CREDITS_USAGE=true
ARG STRIPE_PUBLISHABLE_KEY=
ARG MLHUB_NO_PLAN_FILE_GOOGLE_DRIVE=true
ARG MLHUB_NO_PLAN_LOCALBOOST=true
ARG WASABI_ENDPOINT=
ARG STRIPE_SECRET_KEY=
ARG MLHUB_NO_PLAN_REMOVE_BRANDING=false
ARG WASABI_USE_PATH_STYLE_ENDPOINT=false
ARG MLHUB_NO_PLAN_FILES=true
ARG MLHUB_NO_PLAN_MAX_FILE_SIZE_MB=32
ARG MLHUB_GOOGLE_ANALYTICS_TRACK_APP=1
ARG MLHUB_NO_PLAN_IMAGE_EDITOR=true
ARG STRIPE_STATUS=0
ARG MLHUB_NO_PLAN_SEARCH_MEDIA_ONLINE=true
ARG MLHUB_NO_PLAN_FILE_DROPBOX=true
ARG MLHUB_NO_PLAN_FILE_ONEDRIVE=true
ARG MLHUB_NO_PLAN_SUPPORT=true
ARG MLHUB_NO_PLAN_AFFILIATE=true
ARG MLHUB_GOOGLE_RECAPTCHA_STATUS=0
ARG MLHUB_NO_PLAN_AI_STUDIO=true
ARG MLHUB_NO_PLAN_AI_CAPTION=true
ARG MLHUB_GOOGLE_BUSINESS_STATUS=1
ARG MLHUB_NO_PLAN_AI_CONTENT_PLANNER=true
ARG MLHUB_CONTACT_PHONE=0899789225
ARG MLHUB_CONTACT_LOCATION=01 Nguyễn Văn Linh, Đà Nẵng
ARG MLHUB_NO_PLAN_AI_REPURPOSE=true
ARG STRIPE_WEBHOOK_SECRET=
ARG MLHUB_NO_PLAN_AI_IMAGE=true
ARG MLHUB_NO_PLAN_TEAMS=true
ARG MLHUB_NO_PLAN_MAX_TEAM_MEMBERS=2
ARG MLHUB_NO_PLAN_ADVANCED_CRM=true
ARG MLHUB_NO_PLAN_GOOGLE_LOCATIONS=1
ARG MLHUB_AUTH_LANDING_PAGE_STATUS=1
ARG MLHUB_NO_PLAN_CRM_TAGS=10
ARG MLHUB_AUTH_USER_CHANGE_EMAIL_STATUS=0
ARG MLHUB_NO_PLAN_CRM_SEGMENTS=3
ARG MLHUB_AUTH_SIGNUP_PAGE_STATUS=1
ARG MLHUB_NO_PLAN_CRM_TASKS=20
ARG MLHUB_NO_PLAN_CRM_AUTOMATIONS=2
ARG MLHUB_AUTH_ACTIVATION_EMAIL_STATUS=1
ARG MLHUB_NO_PLAN_CRM_RETENTION_DAYS=90
ARG MLHUB_NO_PLAN_GOOGLE_BUSINESS=true
ARG MLHUB_AUTH_WELCOME_EMAIL_STATUS=1
ARG MLHUB_NO_PLAN_GOOGLE_CONNECTIONS=1
ARG MLHUB_NO_PLAN_GOOGLE_REVIEW_SYNC=true
ARG MLHUB_NO_PLAN_GOOGLE_REVIEW_REPLY=true
ARG MLHUB_NO_PLAN_EMAIL_CONDITIONS=true
ARG MLHUB_NO_PLAN_GOOGLE_INSIGHTS=true
ARG MLHUB_AUTH_TWO_FACTOR_STATUS=1
ARG MLHUB_AUTH_GOOGLE_LOGIN_STATUS=1
ARG MLHUB_NO_PLAN_GOOGLE_POSTS=true
ARG MLHUB_NO_PLAN_EMAIL_AUTOMATION=true
ARG MLHUB_AUTH_GOOGLE_LOGIN_CLIENT_ID=266306087862-0cf2mkerddr0dic2fgj1j25jpb269gg2.apps.googleusercontent.com
ARG MLHUB_NO_PLAN_MAX_EMAIL_AUTOMATIONS=2
ARG MLHUB_NO_PLAN_MAX_EMAIL_TEMPLATES=3
ARG MLHUB_NO_PLAN_EMAILS_PER_MONTH=200
ARG MLHUB_NO_PLAN_EMAIL_DELAY=true
ARG MLHUB_AUTH_USER_CHANGE_USERNAME_STATUS=0
ARG MLHUB_NO_PLAN_WHATSAPP=true
ARG MLHUB_NO_PLAN_MAX_WHATSAPP_RULES=2
ARG MLHUB_NO_PLAN_WEBHOOK_HEADERS=true
ARG MLHUB_NO_PLAN_MAX_WHATSAPP_TEMPLATES=2
ARG MLHUB_AUTH_GOOGLE_LOGIN_CLIENT_SECRET=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
ARG MLHUB_NO_PLAN_WHATSAPP_MESSAGES_PER_MONTH=50
ARG MLHUB_NO_PLAN_WHATSAPP_CLOUD_API=true
ARG MLHUB_AUTH_FACEBOOK_LOGIN_STATUS=0
ARG MLHUB_NO_PLAN_WHATSAPP_TEMPLATE_MSG=true
ARG MLHUB_NO_PLAN_WEBHOOK=true
ARG MLHUB_AUTH_FACEBOOK_LOGIN_APP_ID=
ARG MLHUB_NO_PLAN_MAX_WEBHOOK_RULES=2
ARG MLHUB_NO_PLAN_WEBHOOKS_PER_MONTH=300
ARG MLHUB_AUTH_FACEBOOK_LOGIN_APP_SECRET=
ARG MLHUB_NO_PLAN_MAX_LOYALTY_CARDS=1
ARG MLHUB_AUTH_FACEBOOK_LOGIN_APP_VERSION=v22.0
ARG MLHUB_NO_PLAN_MAX_LOYALTY_CUSTOMERS=100
ARG MLHUB_NO_PLAN_MAX_REFERRAL_CAMPAIGNS=1
ARG MLHUB_NO_PLAN_LOYALTY_REWARDS=true
ARG MLHUB_NO_PLAN_LOYALTY_STAFF_REDEEM=true
ARG MLHUB_AUTH_X_LOGIN_STATUS=0
ARG MLHUB_NO_PLAN_CUSTOM_DOMAINS=true
ARG MLHUB_NO_PLAN_MAX_CUSTOM_DOMAINS=1
ARG MLHUB_AUTH_X_LOGIN_CLIENT_ID=
ARG MLHUB_AUTH_X_LOGIN_CLIENT_SECRET=
ARG MLHUB_CLOUDFLARE_TURNSTILE_STATUS=1
ARG MLHUB_NO_PLAN_WEBHOOK_RETRY=true
ARG MLHUB_NO_PLAN_LOYALTY=true
ARG COOLIFY_URL=https://mlhub.vn,https//www.mlhub.vn
ARG COOLIFY_FQDN=mlhub.vn,https
ARG COOLIFY_BRANCH='main'
ARG COOLIFY_RESOURCE_UUID=mggu45o8q8aso8stbepn622j

LABEL maintainer="MLHUB"
LABEL description="Laravel 13 + Livewire 4 application — Apache, PHP 8.3, MySQL/Redis ready"

ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
ENV PHP_OPCACHE_ENABLE=1

WORKDIR /var/www/html

# Serial extension builds — avoids OOM on small Coolify build hosts (parallel -j$(nproc) spikes RAM during intl/opcache JIT).
ENV MAKEFLAGS=-j1

RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        git \
        unzip \
        zip \
        default-libmysqlclient-dev \
        libpq-dev \
        libzip-dev \
        libpng-dev \
        libjpeg62-turbo-dev \
        libfreetype6-dev \
        libicu-dev \
        libmagic-dev \
        libonig-dev \
        libxml2-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j1 \
        bcmath \
        exif \
        gd \
        intl \
        opcache \
        pcntl \
        pdo_mysql \
        mysqli \
        pdo_pgsql \
        pgsql \
        zip \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && a2enmod rewrite headers \
    && sed -ri 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf \
    && sed -ri 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf \
    && printf '%s\n' \
        '<Directory /var/www/html/public>' \
        '    Options -Indexes +FollowSymLinks' \
        '    AllowOverride All' \
        '    Require all granted' \
        '</Directory>' \
        > /etc/apache2/conf-available/laravel-public.conf \
    && a2enconf laravel-public \
    && apt-get purge -y --auto-remove git unzip \
    && rm -rf /var/lib/apt/lists/* /tmp/pear

RUN { \
        echo 'opcache.enable=1'; \
        echo 'opcache.memory_consumption=256'; \
        echo 'opcache.interned_strings_buffer=16'; \
        echo 'opcache.max_accelerated_files=20000'; \
        echo 'opcache.validate_timestamps=0'; \
        echo 'opcache.save_comments=1'; \
    } > /usr/local/etc/php/conf.d/opcache-recommended.ini

RUN echo "upload_max_filesize = 50M" > /usr/local/etc/php/conf.d/uploads.ini \
    && echo "post_max_size = 50M" >> /usr/local/etc/php/conf.d/uploads.ini \
    && echo "memory_limit = 256M" >> /usr/local/etc/php/conf.d/uploads.ini \
    && php -r "\$required = ['ctype','curl','fileinfo','filter','gd','hash','json','mbstring','openssl','pdo','pdo_mysql','tokenizer','xml','zip']; foreach (\$required as \$e) { if (! extension_loaded(\$e)) { fwrite(STDERR, \"Missing PHP extension: \$e\\n\"); exit(1); } }"

COPY --chown=www-data:www-data . /var/www/html
COPY --from=build --chown=www-data:www-data /app/vendor /var/www/html/vendor

COPY --chmod=755 entrypoint.sh /usr/local/bin/entrypoint.sh

RUN mkdir -p \
        storage/framework/cache/data \
        storage/framework/sessions \
        storage/framework/views \
        storage/logs \
        bootstrap/cache \
        public/livewire \
    && chown -R www-data:www-data storage bootstrap/cache public/livewire \
    && chmod -R 775 storage bootstrap/cache

EXPOSE 80

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["apache2-foreground"]