<?php

namespace Modules\AdminFaker\Support;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;
use Modules\AdminBlogCategories\Models\BlogCategory;
use Modules\AdminBlogs\Models\Blog;
use Modules\AdminBlogTags\Models\BlogTag;
use Modules\AdminFaqs\Models\Faq;
use Modules\AdminNotifications\Models\NotificationManual;
use Modules\AdminNotifications\Models\NotificationManualState;
use Modules\AdminPaymentHistory\Models\PaymentHistory;
use Modules\AdminSupport\Models\SupportCategory;
use Modules\AdminSupport\Models\SupportComment;
use Modules\AdminSupport\Models\SupportLabel;
use Modules\AdminSupport\Models\SupportTicket;
use Modules\AdminSupport\Models\SupportType;
use Modules\AdminUser\Models\Team;
use Modules\AdminUser\Models\User;
use Modules\AppAffiliate\Models\AffiliateCommission;
use Modules\AppAffiliate\Models\AffiliateWithdrawal;
use Modules\AppAffiliate\Support\AffiliateService;
use Modules\AppFiles\Models\AppFile;

/**
 * Admin-site demo content for MLHUB (FAQ, blog, support, affiliate, notifications).
 */
class MLHUBMarketingDemoFaker
{
    /**
     * @param  array<int, AppFile>  $imageFiles
     */
    public function seed(User $user, Team $team, array $imageFiles, array &$counts): void
    {
        $this->createSupportInbox($user, $team, $counts);
        $this->createAffiliateSnapshot($user, $counts);
        $this->createFaqs($counts);
        [$categories, $tags] = $this->createBlogTaxonomy();
        $this->createBlogs($user, $categories, $tags, $imageFiles, $counts);
        $this->createGlobalNotifications($user, $counts);
    }

    public function clear(User $user, array &$deleted): void
    {
        $supportTicketIds = SupportTicket::query()
            ->where('uid', $user->id)
            ->where('title', 'like', '[DEMO]%')
            ->pluck('id');

        if ($supportTicketIds->isNotEmpty()) {
            $deleted['support_comments'] = SupportComment::query()->whereIn('ticket_id', $supportTicketIds)->delete();
            DB::table('support_map_labels')->whereIn('ticket_id', $supportTicketIds)->delete();
            $deleted['support_tickets'] = SupportTicket::query()->whereIn('id', $supportTicketIds)->delete();
        }

        SupportCategory::query()->where('name', 'like', '[DEMO]%')->delete();
        SupportType::query()->where('name', 'like', '[DEMO]%')->delete();
        SupportLabel::query()->where('name', 'like', '[DEMO]%')->delete();

        $demoCommissions = AffiliateCommission::query()
            ->where('affiliate_user_id', $user->id)
            ->where('meta->source', DemoMarker::SOURCE)
            ->get(['id', 'commission', 'status']);

        $demoPaymentHistoryIds = PaymentHistory::query()
            ->where('uid', $user->id)
            ->where('meta->source', DemoMarker::SOURCE)
            ->pluck('id');

        if ($demoCommissions->isNotEmpty()) {
            AffiliateCommission::query()->whereIn('id', $demoCommissions->pluck('id'))->delete();
        }

        if ($demoPaymentHistoryIds->isNotEmpty()) {
            PaymentHistory::query()->whereIn('id', $demoPaymentHistoryIds)->delete();
        }

        $demoWithdrawals = AffiliateWithdrawal::query()
            ->where('affiliate_user_id', $user->id)
            ->where('notes', 'Generated by Admin Faker')
            ->get(['id', 'amount', 'status']);

        $approvedCommissionTotal = (float) $demoCommissions
            ->where('status', AffiliateCommission::STATUS_APPROVED)
            ->sum(fn (AffiliateCommission $commission) => (float) $commission->commission);
        $approvedWithdrawalTotal = (float) $demoWithdrawals
            ->where('status', AffiliateWithdrawal::STATUS_APPROVED)
            ->sum(fn (AffiliateWithdrawal $withdrawal) => (float) $withdrawal->amount);

        if ($demoWithdrawals->isNotEmpty()) {
            AffiliateWithdrawal::query()->whereIn('id', $demoWithdrawals->pluck('id'))->delete();
        }

        if ($demoCommissions->isNotEmpty() || $demoWithdrawals->isNotEmpty()) {
            $profile = app(AffiliateService::class)->ensureProfile($user);
            $volumeScale = MLHUBAdminFakerConfig::volumeScale();
            $profile->forceFill([
                'clicks' => max(0, (int) $profile->clicks - (184 * $volumeScale)),
                'conversions' => max(0, (int) $profile->conversions - $demoCommissions->count()),
                'total_approved' => max(0, (float) $profile->total_approved - $approvedCommissionTotal),
                'total_withdrawal' => max(0, (float) $profile->total_withdrawal - $approvedWithdrawalTotal),
                'total_balance' => max(0, (float) $profile->total_balance - 32.00),
            ])->save();
        }

        $deleted['affiliate_commissions'] = $demoCommissions->count();
        $deleted['affiliate_withdrawals'] = $demoWithdrawals->count();

        $blogIds = Blog::query()->where('slug', 'like', 'demo-preview-%')->pluck('id');

        if ($blogIds->isNotEmpty()) {
            DB::table('blog_tag_maps')->whereIn('blog_id', $blogIds)->delete();
            $deleted['blogs'] = Blog::query()->whereIn('id', $blogIds)->delete();
        }

        $tagIds = BlogTag::query()->where('slug', 'like', 'demo-preview-%')->pluck('id');
        if ($tagIds->isNotEmpty()) {
            DB::table('blog_tag_maps')->whereIn('blog_tag_id', $tagIds)->delete();
            BlogTag::query()->whereIn('id', $tagIds)->delete();
        }

        BlogCategory::query()->where('slug', 'like', 'demo-preview-%')->delete();

        $deleted['faqs'] = Faq::query()->where('slug', 'like', 'demo-preview-%')->delete();

        $globalNotifications = NotificationManual::query()
            ->where('is_global', true)
            ->where('title', 'like', '[DEMO]%')
            ->get(['id']);

        if ($globalNotifications->isNotEmpty()) {
            NotificationManualState::query()
                ->whereIn('notification_manual_id', $globalNotifications->pluck('id'))
                ->delete();

            NotificationManual::query()
                ->whereIn('id', $globalNotifications->pluck('id'))
                ->delete();
        }

        $deleted['global_notifications'] = $globalNotifications->count();
    }

    protected function createSupportInbox(User $user, Team $team, array &$counts): void
    {
        $now = time();

        $category = SupportCategory::query()->firstOrCreate(
            ['name' => '[DEMO] Workspace Help'],
            [
                'id_secure' => Str::random(32),
                'icon' => 'fa-light fa-life-ring',
                'color' => '#ff5f5f',
                'status' => true,
                'changed' => $now,
                'created' => $now,
            ],
        );

        $type = SupportType::query()->firstOrCreate(
            ['name' => '[DEMO] Product Guidance'],
            [
                'id_secure' => Str::random(32),
                'icon' => 'fa-light fa-compass-drafting',
                'color' => '#ff8c42',
                'status' => true,
                'changed' => $now,
                'created' => $now,
            ],
        );

        $label = SupportLabel::query()->firstOrCreate(
            ['name' => '[DEMO] Priority'],
            [
                'id_secure' => Str::random(32),
                'icon' => 'fa-light fa-bolt',
                'color' => '#ffb347',
                'status' => true,
                'changed' => $now,
                'created' => $now,
            ],
        );

        $tickets = MLHUBAdminFakerConfig::load()['marketing']['support_tickets'] ?? [];

        foreach ($tickets as $index => $item) {
            $ticket = SupportTicket::query()->updateOrCreate(
                ['uid' => $user->id, 'title' => $item['title']],
                [
                    'id_secure' => Str::random(32),
                    'open_by' => $user->id,
                    'team_id' => $team->id,
                    'cate_id' => $category->id,
                    'type_id' => $type->id,
                    'content' => $item['content'],
                    'status' => $item['status'],
                    'pin' => $index === 0,
                    'user_read' => $item['user_read'],
                    'admin_read' => $item['admin_read'],
                    'changed' => $now - 1800,
                    'created' => $now - $item['offset'],
                ],
            );

            DB::table('support_map_labels')->updateOrInsert(
                ['ticket_id' => $ticket->id, 'label_id' => $label->id],
                ['ticket_id' => $ticket->id, 'label_id' => $label->id],
            );

            foreach ($item['comments'] ?? [] as $comment) {
                SupportComment::query()->firstOrCreate(
                    [
                        'ticket_id' => $ticket->id,
                        'user_id' => $user->id,
                        'comment' => $comment['comment'],
                    ],
                    [
                        'id_secure' => Str::random(32),
                        'changed' => $now - 1200,
                        'created' => $now - ($comment['offset'] ?? 3600),
                    ],
                );

                $counts['support_comments']++;
            }

            $counts['support_tickets']++;
        }
    }

    protected function createAffiliateSnapshot(User $user, array &$counts): void
    {
        if (! class_exists(AffiliateService::class)) {
            return;
        }

        $affiliate = app(AffiliateService::class);
        $affiliate->ensureReferralCode($user);

        $profile = $affiliate->ensureProfile($user);
        $volumeScale = MLHUBAdminFakerConfig::volumeScale();

        $payments = [
            ['transaction_id' => 'DEMO-AFF-001-'.$user->id, 'amount' => 8_000_000, 'commission_rate' => 15.00, 'commission' => 1_200_000, 'status' => AffiliateCommission::STATUS_APPROVED, 'created_offset' => 172800],
            ['transaction_id' => 'DEMO-AFF-002-'.$user->id, 'amount' => 5_500_000, 'commission_rate' => 15.00, 'commission' => 825_000, 'status' => AffiliateCommission::STATUS_PENDING, 'created_offset' => 86400],
            ['transaction_id' => 'DEMO-AFF-003-'.$user->id, 'amount' => 4_500_000, 'commission_rate' => 15.00, 'commission' => 675_000, 'status' => AffiliateCommission::STATUS_APPROVED, 'created_offset' => 43200],
        ];

        foreach ($payments as $index => $item) {
            $payment = PaymentHistory::query()->updateOrCreate(
                ['transaction_id' => $item['transaction_id']],
                [
                    'id_secure' => Str::random(32),
                    'uid' => $user->id,
                    'plan_id' => $user->plan_id,
                    'from' => 'manual',
                    'currency' => 'VND',
                    'by' => 'admin-faker',
                    'amount' => $item['amount'],
                    'status' => 1,
                    'changed' => time() - $item['created_offset'] + 1200,
                    'created' => time() - $item['created_offset'],
                    'meta' => [
                        'source' => DemoMarker::SOURCE,
                    ],
                ],
            );

            AffiliateCommission::query()->updateOrCreate(
                ['payment_history_id' => $payment->id],
                [
                    'id_secure' => Str::random(32),
                    'affiliate_user_id' => $user->id,
                    'referred_user_id' => $user->id,
                    'amount' => $item['amount'],
                    'commission_rate' => $item['commission_rate'],
                    'commission' => $item['commission'],
                    'status' => $item['status'],
                    'meta' => [
                        'source' => DemoMarker::SOURCE,
                        'sample' => $index + 1,
                    ],
                    'approved_at' => $item['status'] === AffiliateCommission::STATUS_APPROVED ? now()->subHours($index + 5) : null,
                    'created_at' => now()->subSeconds($item['created_offset']),
                    'updated_at' => now()->subSeconds(max(0, $item['created_offset'] - 1800)),
                ],
            );

            $counts['affiliate_commissions']++;
        }

        $withdrawals = [
            ['amount' => 450000, 'payment_method' => 'Chuyển khoản ngân hàng', 'payment_details' => 'Vietcombank – 0123456789 – NGUYEN VAN A', 'status' => AffiliateWithdrawal::STATUS_APPROVED, 'offset' => 28800],
            ['amount' => 625000, 'payment_method' => 'Chuyển khoản ngân hàng', 'payment_details' => 'Techcombank – đang chờ duyệt chi', 'status' => AffiliateWithdrawal::STATUS_PENDING, 'offset' => 10800],
        ];

        foreach ($withdrawals as $withdrawal) {
            AffiliateWithdrawal::query()->create([
                'id_secure' => Str::random(32),
                'affiliate_user_id' => $user->id,
                'amount' => $withdrawal['amount'],
                'payment_method' => $withdrawal['payment_method'],
                'payment_details' => $withdrawal['payment_details'],
                'notes' => 'Generated by Admin Faker',
                'status' => $withdrawal['status'],
                'processed_at' => $withdrawal['status'] === AffiliateWithdrawal::STATUS_APPROVED ? now()->subHours(4) : null,
                'created_at' => now()->subSeconds($withdrawal['offset']),
                'updated_at' => now()->subSeconds(max(0, $withdrawal['offset'] - 1200)),
            ]);

            $counts['affiliate_withdrawals']++;
        }

        $profile->forceFill([
            'clicks' => (int) $profile->clicks + (184 * $volumeScale),
            'conversions' => (int) $profile->conversions + (count($payments) * $volumeScale),
            'total_approved' => (float) $profile->total_approved + (75.00 * $volumeScale),
            'total_withdrawal' => (float) $profile->total_withdrawal + 18.00,
            'total_balance' => (float) $profile->total_balance + 32.00,
        ])->save();
    }

    protected function createFaqs(array &$counts): void
    {
        $static = MLHUBAdminFakerConfig::load()['marketing']['faqs'] ?? [];
        $target = MLHUBAdminFakerConfig::marketingFaqTarget();
        $generated = MLHUBMarketingContentGenerator::faqs(max(0, $target - count($static)));
        $faqs = array_merge($static, $generated);

        foreach ($faqs as $faq) {
            Faq::query()->updateOrCreate(
                ['slug' => $faq['slug']],
                [
                    'id_secure' => Str::random(32),
                    'title' => $faq['title'],
                    'title_translations' => ['en' => $faq['title'], 'vi' => $faq['title']],
                    'content' => $faq['content'],
                    'content_translations' => ['en' => $faq['content'], 'vi' => $faq['content']],
                    'status' => 1,
                    'changed' => time(),
                    'created' => time(),
                ],
            );

            $counts['faqs']++;
        }
    }

    /**
     * @return array{0: \Illuminate\Support\Collection<int, BlogCategory>, 1: \Illuminate\Support\Collection<int, BlogTag>}
     */
    protected function createBlogTaxonomy(): array
    {
        $now = time();
        $sort = 10;

        $categories = collect(MLHUBMarketingContentGenerator::blogCategories())->map(function (array $row) use (&$sort, $now): BlogCategory {
            return BlogCategory::query()->create([
                'id_secure' => Str::random(32),
                'name' => $row['name'],
                'name_translations' => ['en' => $row['name_en'], 'vi' => $row['name']],
                'description' => $row['description'],
                'description_translations' => ['en' => $row['description'], 'vi' => $row['description']],
                'slug' => $row['slug'],
                'icon' => 'fa-light fa-qrcode',
                'color' => '#ff5f5f',
                'status' => 1,
                'sort_order' => $sort,
                'changed' => $now,
                'created' => $now,
            ]);
        });

        $tags = collect(MLHUBMarketingContentGenerator::blogTags())->map(function (array $tag) use ($now): BlogTag {
            return BlogTag::query()->create([
                'id_secure' => Str::random(32),
                'name' => $tag['name'],
                'name_translations' => ['en' => $tag['name_en'], 'vi' => $tag['name']],
                'description' => 'Thẻ demo MLHUB — SaaS marketing cho hộ kinh doanh & SOHO Đà Nẵng.',
                'description_translations' => ['en' => 'MLHUB demo tag — SOHO Da Nang.', 'vi' => 'Thẻ demo MLHUB — SaaS marketing cho hộ kinh doanh & SOHO Đà Nẵng.'],
                'slug' => $tag['slug'],
                'color' => '#ff8c42',
                'status' => 1,
                'changed' => $now,
                'created' => $now,
            ]);
        });

        return [$categories, $tags];
    }

    /**
     * @param  \Illuminate\Support\Collection<int, BlogCategory>  $categories
     * @param  \Illuminate\Support\Collection<int, BlogTag>  $tags
     * @param  array<int, AppFile>  $imageFiles
     */
    protected function createBlogs(User $user, $categories, $tags, array $imageFiles, array &$counts): void
    {
        $now = time();
        $imageResolver = app(MLHUBDemoImageResolver::class);
        $static = MLHUBAdminFakerConfig::load()['marketing']['blogs'] ?? [];
        $target = MLHUBAdminFakerConfig::marketingBlogTarget();
        $generated = MLHUBMarketingContentGenerator::blogs(max(0, $target - count($static)));

        foreach (array_merge($static, $generated) as $index => $blog) {
            $image = $imageResolver->random($imageFiles);
            $categoryIndex = (int) ($blog['category_index'] ?? ($index % max(1, $categories->count())));
            $category = $categories->values()[$categoryIndex % $categories->count()];
            $content = $blog['content'] ?? (
                '<p>'.$blog['excerpt'].'</p><p>Bài demo MLHUB minh họa cách hộ kinh doanh kết hợp chiến dịch QR, landing page và báo cáo trên một nền tảng.</p>'
            );
            $publishedAt = $now - (($index % 720) * 86400);

            $entry = Blog::query()->updateOrCreate(
                ['slug' => $blog['slug']],
                [
                    'id_secure' => Str::random(32),
                    'blog_category_id' => $category->id,
                    'title' => $blog['title'],
                    'title_translations' => ['en' => $blog['title'], 'vi' => $blog['title']],
                    'excerpt' => $blog['excerpt'],
                    'excerpt_translations' => ['en' => $blog['excerpt'], 'vi' => $blog['excerpt']],
                    'content' => $content,
                    'content_translations' => ['en' => $content, 'vi' => $content],
                    'meta_title' => $blog['title'],
                    'meta_description' => $blog['excerpt'],
                    'canonical_url' => null,
                    'og_image' => $imageResolver->url($image),
                    'thumbnail' => $imageResolver->url($image),
                    'status' => 1,
                    'published_at' => $publishedAt,
                    'changed' => $now,
                    'created' => $now,
                ],
            );

            $tagIndexes = $blog['tag_indexes'] ?? [$index % max(1, $tags->count()), ($index + 2) % max(1, $tags->count())];
            $tagIds = collect($tagIndexes)
                ->map(fn (int $tagIndex): ?int => $tags->values()[$tagIndex % $tags->count()]->id ?? null)
                ->filter()
                ->unique()
                ->values()
                ->all();

            if ($tagIds !== []) {
                $entry->tags()->syncWithoutDetaching($tagIds);
            }

            $counts['blogs']++;
        }
    }

    protected function createGlobalNotifications(User $user, array &$counts): void
    {
        $rows = MLHUBAdminFakerConfig::load()['marketing']['global_notifications'] ?? [];

        foreach ($rows as $index => $row) {
            NotificationManual::query()->updateOrCreate(
                ['title' => $row['title'], 'is_global' => true],
                [
                    'id_secure' => Str::random(32),
                    'message' => $row['message'],
                    'url' => $this->demoRouteUrl(
                        (string) ($row['url_route'] ?? ''),
                        (string) ($row['url_fallback'] ?? ''),
                    ),
                    'type' => $row['type'],
                    'created_by' => $user->id,
                    'created_at' => now()->subMinutes(($index + 1) * 9),
                    'updated_at' => now()->subMinutes(($index + 1) * 9),
                ],
            );

            $counts['global_notifications']++;
        }
    }

    protected function demoRouteUrl(string $routeName, string $fallbackPath = ''): string
    {
        if (Route::has($routeName)) {
            return route($routeName);
        }

        return url($fallbackPath !== '' ? $fallbackPath : '/');
    }
}
