import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(__dirname, '../data/ai_templates_vi_map_2.json');

/** @type {Record<string, string>} */
const viMap = {
  "65a10d7c2c14a": "Tạo bài đăng mạng xã hội mở rộng về các yếu tố khác nhau ảnh hưởng đến {{ hành vi người tiêu dùng/nhân viên }}.",
  "65a10d7c2c5ca": "Tạo bài đăng mạng xã hội mở rộng về tác động của {{ nghề nghiệp/ngành }} đối với xã hội của chúng ta.",
  "65a10d7c2ca4d": "Tạo bài đăng mạng xã hội mở rộng về các góc nhìn khác nhau về {{ khái niệm/ý tưởng triết học }}.",
  "65a10d7c2cf29": "Tạo bài đăng mạng xã hội mở rộng về {{ xu hướng }} và mối liên hệ với {{ giá trị văn hóa/xã hội/chính trị nhất định }}.",
  "65a10d7c2d43a": "Tạo bài đăng mạng xã hội mở rộng về những khía cạnh của {{ chủ đề }} thường bị bỏ qua.",
  "65a10d7c2d85e": "Tạo bài đăng mạng xã hội mở rộng về khuyến nghị sau và các thách thức khi triển khai:",
  "65a10d7c2dbe7": "Tóm tắt nội dung sau và chuyển thành bài đăng mạng xã hội:",
  "65a10d7c2dfe9": "Đơn giản hóa đoạn văn sau:",
  "65a10d7c2e3f0": "Tóm tắt đoạn văn sau trong một câu:",
  "65a10d7c2e7e2": "Tóm tắt các ý chính của nội dung sau:",
  "65a10d7c2ebed": "Tạo bài đăng mạng xã hội nắm bắt tinh thần của thông điệp sau:",
  "65a10d7c2efee": "Rút gọn văn bản sau thành phiên bản ngắn hơn nhưng vẫn giữ các ý chính:",
  "65a10d7c2f45c": "Viết bản tóm tắt ngắn gọn về văn bản sau:",
  "65a10d7c2f95d": "Dùng phép so sánh hoặc ẩn dụ để giải thích khái niệm sau bằng ngôn ngữ đơn giản hơn:",
  "65a10d7c2fd18": "Viết lại câu sau bằng ngôn ngữ đơn giản hơn:",
  "65a10d7c300d8": "Phân tích các bước hoặc thành phần của quy trình sau:",
  "65a10d7c304b4": "Tóm tắt nghiên cứu sau thành ba điểm rút ra chính:",
  "65a10d7c308e1": "Đơn giản hóa văn bản chuyên ngành sau cho {{ đối tượng mục tiêu }}:",
  "65a10d7c30cc9": "Đơn giản hóa quy trình kỹ thuật sau thành hướng dẫn từng bước:",
  "65a10d7c310bf": "Đơn giản hóa lời chào hàng tiếp thị sau cho {{ đối tượng }}:",
  "65a10d7c314c8": "Đơn giản hóa văn bản sau thành các mẹo thực tế:",
  "65a10d7c31902": "Đơn giản hóa văn bản sau thành khẩu hiệu bắt tai:",
  "65a10d7c31d2c": "Khuyến khích {{ chân dung khách hàng lý tưởng }} dùng thử {{ sản phẩm/dịch vụ }} theo khung \"Thiên kiến đền đáp\". Tuy nhiên, tránh nhắc trực tiếp khung \"Thiên kiến đền đáp\" trong nội dung. Đưa ra phần thưởng hoặc quà tặng hấp dẫn khi khách thực hiện một hành động để tạo cảm giác có nghĩa vụ đáp lại.",
  "65a10d7c32197": "Dùng khung \"Thiên kiến xác nhận\" để chạm vào niềm tin sẵn có của {{ chân dung khách hàng lý tưởng }} về {{ chủ đề }}. Tuy nhiên, tránh nhắc trực tiếp khung \"Thiên kiến xác nhận\" trong nội dung. Trình bày thông tin phù hợp giá trị và quan điểm của họ, khuyến khích họ hành động và dùng thử {{ sản phẩm/dịch vụ }} của chúng tôi.",
  "65a10d7c32608": "Làm nổi bật thành công có thể đạt được với {{ sản phẩm/dịch vụ }} của chúng tôi và giảm thiểu hiểu lầm tiêu cực bằng khung \"Định khung tích cực\". Tuy nhiên, tránh nhắc trực tiếp khung \"Định khung tích cực\" trong nội dung. Giải thích sản phẩm giúp {{ chân dung khách hàng lý tưởng }} đạt {{ kết quả mong muốn }} như thế nào.",
  "65a10d7c32b23": "Dùng lý thuyết \"So sánh xã hội\" để giới thiệu thành công của những người đã dùng {{ sản phẩm/dịch vụ }} của chúng tôi. Tuy nhiên, tránh nhắc trực tiếp lý thuyết \"So sánh xã hội\" trong nội dung. Nhấn mạnh cách sản phẩm giúp {{ chân dung khách hàng lý tưởng }} đạt kết quả tương tự.",
  "65a10d7c32fdc": "Giới thiệu thành công và lợi ích của {{ sản phẩm/dịch vụ }} cho {{ chân dung khách hàng lý tưởng }} theo lý thuyết \"Học tập xã hội\" và khuyến khích khách hàng tiềm năng học hỏi từ trải nghiệm tích cực của khách hàng hiện tại. Tuy nhiên, tránh nhắc trực tiếp lý thuyết \"Học tập xã hội\" trong nội dung. Mô tả kết quả tích cực người khác đã đạt được và đưa ra ưu đãi để khách mới tự trải nghiệm. Mục tiêu bài đăng là truyền cảm hứng hành động.",
  "65a10d7c333bd": "Theo lý thuyết \"Hiệu quả bản thân\", viết bài đăng mạng xã hội giúp {{ chân dung khách hàng lý tưởng }} tự tin hơn và cảm thấy có thể đạt mục tiêu với {{ sản phẩm/dịch vụ }} của chúng tôi. Tuy nhiên, tránh nhắc trực tiếp lý thuyết \"Hiệu quả bản thân\" trong nội dung. Làm nổi bật thành công của người khác khi dùng sản phẩm và cung cấp tài nguyên, hỗ trợ để họ sẵn sàng hành động.",
  "65a10d7c337e4": "Viết bài đăng mạng xã hội theo chiến lược quảng cáo \"Gợi cảm xúc\" để {{ chân dung khách hàng lý tưởng }} gắn {{ sản phẩm/dịch vụ }} với trải nghiệm và cảm xúc tích cực. Tuy nhiên, tránh nhắc trực tiếp chiến lược \"Gợi cảm xúc\" trong nội dung. Chỉ dùng khung này để làm {{ sản phẩm/dịch vụ }} hấp dẫn hơn về mặt cảm xúc.",
  "65a10d7c33beb": "Viết bài đăng mạng xã hội nêu bật lợi ích và giá trị khi dùng {{ sản phẩm/dịch vụ }} cho {{ chân dung khách hàng lý tưởng }}. Dùng hiệu ứng \"Chưa hết đâu\" — bắt đầu bằng một lợi ích rồi tiếp tục bằng lợi ích lớn hơn — mà không nhắc trực tiếp hiệu ứng này. Nhấn mạnh cách công cụ giúp {{ chân dung khách hàng lý tưởng }} đạt mục tiêu. Kết thúc bằng lời khuyến khích {{ chân dung khách hàng lý tưởng }} dùng thử {{ sản phẩm/dịch vụ }}.",
  "65a10d7c34012": "Viết bài đăng mạng xã hội theo khung \"Ngụy biện chi phí chìm\" để thuyết phục {{ chân dung khách hàng lý tưởng }} tiếp tục dùng {{ sản phẩm/dịch vụ }}. Tuy nhiên, tránh nhắc trực tiếp khung \"Ngụy biện chi phí chìm\" trong nội dung. Nhấn mạnh nguồn lực đã bỏ ra sẽ tăng lợi nhuận đầu tư. Nêu rõ tổn thất và hối tiếc nếu không dùng {{ sản phẩm/dịch vụ }}.",
  "65a10d7c34415": "Tạo bài đăng mạng xã hội theo \"Nguyên lý khan hiếm\" để tạo cảm giác cấp bách và khao khát {{ sản phẩm/dịch vụ }} của chúng tôi ở {{ chân dung khách hàng lý tưởng }}. Tuy nhiên, tránh nhắc trực tiếp \"Nguyên lý khan hiếm\" trong nội dung. Làm nổi bật số lượng có hạn hoặc tính độc quyền của sản phẩm, kèm lời kêu gọi hành động rõ ràng để khách nắm cơ hội trước khi quá muộn.",
  "65a10d7c3481d": "Viết bài đăng mạng xã hội theo khung \"Ngại mất mát\" để thúc đẩy {{ chân dung khách hàng lý tưởng }} bắt đầu dùng {{ sản phẩm/dịch vụ }} vì sợ bỏ lỡ lợi ích sản phẩm mang lại. Tuy nhiên, tránh nhắc trực tiếp khung \"Ngại mất mát\" trong nội dung.",
  "65a10d7c34c3c": "Tạo bài đăng mạng xã hội theo khung \"Sợ bỏ lỡ\" kết hợp khuyến mãi có hạn hấp dẫn để tạo cảm giác cấp bách cho {{ chân dung khách hàng lý tưởng }} mua {{ sản phẩm/dịch vụ }}. Tuy nhiên, tránh nhắc trực tiếp khung \"Sợ bỏ lỡ\" trong nội dung.",
  "65a10d7c35118": "Viết bài đăng mạng xã hội theo khung \"Hiệu ứng định khung\" để trình bày thông tin về {{ sản phẩm/dịch vụ }} của chúng tôi theo cách ảnh hưởng nhận thức và quyết định của {{ chân dung khách hàng lý tưởng }}. Tuy nhiên, tránh nhắc trực tiếp khung \"Hiệu ứng định khung\" trong nội dung. Cân nhắc các cách định khung khác nhau (ví dụ: được/mất, tích cực/tiêu cực) và chọn khung thuận lợi nhất cho sản phẩm.",
  "65a10d7c35624": "Tạo bài đăng mạng xã hội theo khung \"Điều kiện học cổ điển\" để gắn {{ sản phẩm/dịch vụ }} của chúng tôi với kết quả tích cực. Tuy nhiên, tránh nhắc trực tiếp khung \"Điều kiện học cổ điển\" trong nội dung.",
  "65a10d7c35a95": "Viết bài đăng mạng xã hội theo khung \"Hiệu ứng hào quang\" để gán phẩm chất tích cực cho {{ sản phẩm/dịch vụ }} dựa trên {{ đặc điểm/tính chất tích cực }}. Tuy nhiên, tránh nhắc trực tiếp khung \"Hiệu ứng hào quang\" trong nội dung.",
  "65a10d7c35e86": "Tạo bài đăng mạng xã hội cho {{ phân khúc khách hàng }} giải quyết ba lo ngại tiềm ẩn khi dùng {{ sản phẩm/dịch vụ }} theo khung \"Lý thuyết không nhất quán nhận thức\". Tuy nhiên, tránh nhắc trực tiếp \"Lý thuyết không nhất quán nhận thức\" trong nội dung. Thay vào đó, lồng ghép nguyên tắc lý thuyết một cách tự nhiên bằng lập luận logic để xoa dịu niềm tin mâu thuẫn. Mục tiêu là giảm nghi ngờ và khuyến khích họ dùng thử {{ sản phẩm/dịch vụ }} từ {{ tên công ty }}. Bài đăng cần nêu cách {{ sản phẩm/dịch vụ }} giúp {{ phân khúc khách hàng }} vượt qua thách thức, kèm lời chứng thực và câu chuyện thành công của người dùng hài lòng khác.",
  "65a10d7c36258": "Chạm vào bản sắc của {{ chân dung khách hàng lý tưởng }} theo lý thuyết \"Bản sắc xã hội\". Tuy nhiên, tránh nhắc trực tiếp lý thuyết \"Bản sắc xã hội\" trong nội dung. Làm nổi bật cách {{ sản phẩm/dịch vụ }} của chúng tôi phù hợp bản sắc và giá trị xã hội của họ, kèm lời chứng thực và ví dụ người trong nhóm xã hội của họ dùng sản phẩm thành công để tạo cảm giác thuộc về và tích cực.",
  "65a10d7c3664a": "Theo thang nhu cầu Maslow, nói đến nhu cầu hiện tại của {{ chân dung khách hàng lý tưởng }} trong bài đăng mạng xã hội. Tuy nhiên, tránh nhắc trực tiếp thang nhu cầu Maslow trong nội dung. Làm nổi bật cách {{ sản phẩm/dịch vụ }} của chúng tôi giúp họ đáp ứng nhu cầu này. Dùng ngôn ngữ gần gũi với thách thức và mục tiêu hiện tại của họ.",
  "65a10d7c36a3e": "Tạo bài đăng mạng xã hội khuyến khích {{ chân dung khách hàng lý tưởng }} dùng thử {{ sản phẩm/dịch vụ }} theo khung \"Thiên kiến neo\". Tuy nhiên, tránh nhắc trực tiếp khung \"Thiên kiến neo\" trong nội dung. Làm nổi bật tính năng hoặc lợi ích giá trị cao và neo vào mức giá thấp hơn hoặc giá trị cảm nhận khác. Đưa giảm giá hoặc quà tặng có thời hạn để tạo cảm giác cấp bách và thúc đẩy mua hàng.",
  "65a10d7c3725d": "Tạo bài đăng mạng xã hội khuyến khích {{ chân dung khách hàng lý tưởng }} dùng thử {{ sản phẩm/dịch vụ }} theo kỹ thuật \"Chân trong cửa\". Tuy nhiên, tránh nhắc trực tiếp kỹ thuật \"Chân trong cửa\" trong nội dung. Bắt đầu bằng yêu cầu nhỏ, như đăng ký dùng thử miễn phí hoặc để lại địa chỉ thư điện tử, rồi tiếp tục yêu cầu lớn hơn như nâng cấp gói trả phí hoặc mua hàng. Hành động nhỏ ban đầu tạo cam kết và tăng khả năng hành động tiếp theo.",
  "65a10d7c37652": "Tạo bài đăng mạng xã hội làm nổi bật sự khan hiếm của {{ sản phẩm/dịch vụ }} theo khung \"Số lượng có hạn\". Tuy nhiên, tránh nhắc trực tiếp khung \"Số lượng có hạn\" trong nội dung. Tạo bài đăng nhấn mạnh số lượng hoặc tình trạng còn hàng hạn chế của {{ sản phẩm/dịch vụ }}. Dùng cụm như \"ưu đãi có thời hạn\" hoặc \"chỉ còn số lượng giới hạn\" để tạo cảm giác cấp bách và thúc đẩy mua hàng.",
  "65a10d7c37a24": "Tạo bài đăng mạng xã hội khuyến khích {{ chân dung khách hàng lý tưởng }} dùng thử {{ sản phẩm/dịch vụ }} theo khung \"Thiên kiến thẩm quyền\". Tuy nhiên, tránh nhắc trực tiếp khung \"Thiên kiến thẩm quyền\" trong nội dung. Giới thiệu chuyên gia hoặc nhân vật có uy tín trong ngành bạn ủng hộ sản phẩm hoặc dịch vụ. Dùng cụm như \"được khuyên dùng bởi\" hoặc \"được phê duyệt bởi\" để tạo niềm tin và uy tín.",
  "65a10d7c37e21": "Tạo bài đăng mạng xã hội theo \"Hiệu ứng ưu tiên đầu tiên\" để quảng bá {{ sản phẩm/dịch vụ }} và tạo ấn tượng mạnh với {{ chân dung khách hàng lý tưởng }}. Tuy nhiên, tránh nhắc trực tiếp \"Hiệu ứng ưu tiên đầu tiên\" trong nội dung. Đặt thông điệp hấp dẫn hoặc thu hút nhất lên đầu.",
  "65a10d7c381f2": "Tạo bài đăng mạng xã hội theo \"Hiệu ứng hài hước\" để {{ chân dung khách hàng lý tưởng }} dễ tiếp nhận thông điệp quảng bá về {{ sản phẩm/dịch vụ }}. Tuy nhiên, tránh nhắc trực tiếp \"Hiệu ứng hài hước\" trong nội dung. Dùng nội dung vui nhộn hoặc giải trí liên quan {{ sản phẩm/dịch vụ }} để bài đăng dễ nhớ hơn.",
  "65a10d7c385c1": "Tạo bài đăng mạng xã hội khuyến khích {{ chân dung khách hàng lý tưởng }} dùng thử {{ sản phẩm/dịch vụ }} theo \"Hiệu ứng nổi bật\". Tuy nhiên, tránh nhắc trực tiếp \"Hiệu ứng nổi bật\" trong nội dung. Làm nổi bật khía cạnh độc đáo hoặc khác biệt của {{ sản phẩm/dịch vụ }} để nổi bật so với đối thủ và dễ nhớ với khách hàng tiềm năng.",
  "65a10d7c38a03": "Tạo bài đăng mạng xã hội theo lý thuyết \"Khoảng trống thông tin\" để khơi gợi sự tò mò của {{ chân dung khách hàng lý tưởng }}. Tuy nhiên, tránh nhắc trực tiếp lý thuyết \"Khoảng trống thông tin\" trong nội dung. Gợi ý điều thú vị liên quan {{ sản phẩm/dịch vụ }}, nhưng chỉ tiết lộ đầy đủ sau khi khách thực hiện hành động, ví dụ đăng ký nhận bản tin.",
  "65a10d7c38e0e": "Tạo bài đăng mạng xã hội theo khung \"Hiệu ứng mồi nhử\" để ảnh hưởng quyết định mua {{ sản phẩm/dịch vụ }} của {{ chân dung khách hàng lý tưởng }}. Tuy nhiên, tránh nhắc trực tiếp khung \"Hiệu ứng mồi nhử\" trong nội dung. Đưa ra các lựa chọn {{ sản phẩm/dịch vụ/gói đăng ký }} khác nhau và làm nổi bật {{ sản phẩm/dịch vụ/gói đăng ký cụ thể }} là lựa chọn hấp dẫn nhất.",
  "65a10d7c39204": "Tạo bài đăng mạng xã hội theo khung \"Lời nguyền kiến thức\" để giải thích {{ sản phẩm/dịch vụ }} của chúng tôi theo cách {{ chân dung khách hàng lý tưởng }} dễ hiểu. Tuy nhiên, tránh nhắc trực tiếp khung \"Lời nguyền kiến thức\" trong nội dung. Tránh thuật ngữ chuyên ngành hoặc kỹ thuật, thay vào đó dùng ngôn ngữ đơn giản để làm nổi bật lợi ích.",
  "65a10d7c3960e": "Viết bài đăng mạng xã hội theo khung \"Khoảng trống tò mò\" để khiến {{ chân dung khách hàng lý tưởng }} tò mò và quan tâm đến {{ sản phẩm/dịch vụ }} của chúng tôi. Tuy nhiên, tránh nhắc trực tiếp khung \"Khoảng trống tò mò\" trong nội dung. Đặt câu hỏi hoặc tạo bí ẩn mà {{ sản phẩm/dịch vụ }} có thể giải quyết, khơi dậy mong muốn tìm hiểu thêm.",
  "65a10d7c399d8": "Viết nội dung theo cấu trúc Thu hút-Quan tâm-Khao khát-Hành động cho nội dung sau:",
  "65a10d7c39da2": "Viết nội dung theo cấu trúc Trước-Sau-Cầu nối về nội dung sau:",
  "65a10d7c3a17e": "Viết nội dung theo cấu trúc Vấn đề-Khuấy động-Giải quyết cho nội dung sau. Viết nội dung theo cấu trúc Thu hút-Quan tâm-Khao khát-Hành động cho nội dung sau.",
  "65a10d7c3a538": "Viết nội dung theo cấu trúc Vấn đề-Khuếch đại-Câu chuyện-Chuyển hóa-Đề xuất cho nội dung sau:",
  "65a10d7c3a902": "Viết nội dung theo cấu trúc Đồng ý-Cam kết-Xem trước cho nội dung sau. Viết nội dung theo cấu trúc Tính năng-Ưu điểm-Lợi ích cho nội dung sau.",
  "65a10d7c3ad1b": "Viết nội dung theo cấu trúc Tính năng-Bằng chứng-Lợi ích-Hành động cho nội dung sau:",
  "65a10d7c3b0eb": "Viết nội dung theo cấu trúc Hình dung-Cam kết-Chứng minh-Thúc đẩy cho nội dung sau:",
  "65a10d7c3b506": "Viết nội dung theo cấu trúc Dừng lại-Nhìn-Hành động-Tiếp tục cho nội dung sau:",
  "65a10d7c3b967": "Viết nội dung theo cấu trúc Tình huống-Vấn đề phát sinh-Câu hỏi-Trả lời cho nội dung sau:",
  "65a10d7c3bd9b": "Viết nội dung theo cấu trúc Uy tín-Logic-Thu hút-Thúc đẩy cho nội dung sau:",
  "65a10d7c3c2c3": "Theo khung \"Tình huống-Vấn đề phát sinh-Giải pháp\", viết prompt mạng xã hội trình bày {{ tình huống }} mà {{ chân dung khách hàng lý tưởng }} đang gặp. Thảo luận {{ vấn đề phát sinh }} từ tình huống đó và hỏi người đọc chia sẻ cách {{ sản phẩm/dịch vụ }} của chúng tôi có thể là {{ giải pháp }} cho vấn đề. Cuối cùng, kết bằng lời kêu gọi hành động khuyến khích tìm hiểu thêm giải pháp của chúng tôi.",
  "65a10d7c3c76f": "Theo khung \"Đề xuất giá trị cảm xúc\", viết prompt mạng xã hội chạm vào {{ nhu cầu cảm xúc }} của {{ chân dung khách hàng lý tưởng }}. Mời người đọc chia sẻ trải nghiệm cá nhân với những cảm xúc đó, xác định {{ cảm xúc mong muốn }}, tạo {{ câu chuyện }} gợi cảm xúc đó, và hỏi người đọc chia sẻ cách {{ sản phẩm/dịch vụ }} của chúng tôi đã đáp ứng nhu cầu cảm xúc đó.",
  "65a10d7c3cc17": "Viết prompt mạng xã hội theo khung \"Bản đồ hành trình khách hàng\" hình dung hành trình từ {{ nhận biết }} đến {{ chuyển đổi }} của {{ chân dung khách hàng lý tưởng }}. Mời người đọc chia sẻ nỗi đau ở từng giai đoạn, làm nổi bật cách {{ sản phẩm/dịch vụ }} của chúng tôi giải quyết các vấn đề đó, và hỏi họ sẽ dùng sản phẩm để {{ cải thiện tình huống của họ }} như thế nào.",
  "65a10d7c3d01b": "Theo khung \"Phễu marketing\", viết prompt mạng xã hội nhắm giai đoạn {{ nhận biết/cân nhắc/chuyển đổi }} trong hành trình khách hàng và phù hợp mục tiêu từng giai đoạn. Làm nổi bật {{ tính năng }} của {{ sản phẩm/dịch vụ }} và hỏi người đọc chia sẻ cách sản phẩm có thể {{ giải quyết vấn đề }} hoặc {{ đạt mục tiêu }} cho {{ chân dung khách hàng lý tưởng }}.",
  "65a10d7c3d3ee": "Viết prompt mạng xã hội theo khung \"Bản đồ đồng cảm\" để hiểu suy nghĩ, cảm xúc và nhu cầu của {{ chân dung khách hàng lý tưởng }}. Mời người đọc chia sẻ nỗi đau và cách {{ sản phẩm/dịch vụ }} của chúng tôi có thể đáp ứng {{ suy nghĩ/cảm xúc/nhu cầu }} của họ. Làm nổi bật cách sản phẩm cải thiện tình huống và hỏi họ sẽ dùng sản phẩm trong cuộc sống hàng ngày như thế nào.",
  "65a10d7c3d7ba": "Theo khung \"Phù hợp sản phẩm-thị trường\", giải thích cách {{ sản phẩm/dịch vụ }} của chúng tôi phù hợp hoàn hảo với nhu cầu và nỗi đau của {{ chân dung khách hàng lý tưởng }}. Xác định vấn đề cụ thể thị trường mục tiêu gặp phải và tạo prompt mạng xã hội giải thích cách sản phẩm giải quyết các vấn đề này. Dùng bằng chứng hoặc lời chứng thực để củng cố và nhấn mạnh lợi ích khi dùng sản phẩm.",
  "65a10d7c3db83": "Theo khung \"Phá bỏ huyền thoại\", xác định và bác bỏ hiểu lầm hoặc huyền thoại phổ biến về {{ sản phẩm/dịch vụ }} của chúng tôi. Cung cấp {{ sự thật }} và {{ bằng chứng }} để củng cố và giúp {{ chân dung khách hàng lý tưởng }} hiểu đúng lợi ích thực sự của sản phẩm/dịch vụ.",
  "65a10d7c3df83": "Viết prompt mạng xã hội theo khung \"Kể chuyện\" để tạo câu chuyện ngắn xoay quanh {{ sản phẩm/dịch vụ }} của chúng tôi. Dùng nhân vật, cốt truyện và bối cảnh để thu hút {{ chân dung khách hàng lý tưởng }} và xây dựng kết nối cảm xúc. Mời người đọc chia sẻ trải nghiệm của họ với sản phẩm/dịch vụ và cách nó gắn vào câu chuyện riêng của họ.",
  "65a10d7c3e395": "Viết prompt mạng xã hội theo khung \"Hỏi-Đáp\" bắt đầu bằng {{ câu hỏi }} liên quan {{ chân dung khách hàng lý tưởng }}. Đưa câu trả lời ngắn gọn, hữu ích và mời người đọc chia sẻ suy nghĩ về chủ đề cũng như cách sản phẩm/dịch vụ của chúng tôi giúp họ giải quyết câu hỏi đó.",
  "65a10d7c3e76e": "Theo khung \"So sánh-Đối chiếu\", viết prompt mạng xã hội so sánh và đối chiếu hai hoặc nhiều lựa chọn hoặc ý tưởng để giúp {{ chân dung khách hàng lý tưởng }} ra quyết định sáng suốt. Mời người đọc chia sẻ ý kiến về các lựa chọn được trình bày và cách sản phẩm/dịch vụ của chúng tôi giúp họ quyết định.",
  "65a10d7c3eb3d": "Dùng khung \"Hướng dẫn cách làm\" để cung cấp hướng dẫn từng bước hoàn thành {{ nhiệm vụ }} hoặc đạt {{ mục tiêu }} cho {{ chân dung khách hàng lý tưởng }}. Khuyến khích người đọc chia sẻ trải nghiệm hoàn thành nhiệm vụ hoặc đạt mục tiêu, và cách sản phẩm/dịch vụ của chúng tôi đã hỗ trợ họ.",
  "65a10d7c3ef09": "Xác định vấn đề {{ chân dung khách hàng lý tưởng }} đang gặp và đưa ra giải pháp qua {{ sản phẩm/dịch vụ }} của chúng tôi theo khung \"Vấn đề-Giải pháp\". Giải thích rõ cách sản phẩm giải quyết vấn đề và cải thiện tình huống của họ.",
  "65a10d7c3f280": "Làm bài đăng mạng xã hội hiệu quả và dễ nhớ hơn bằng khung \"Quy tắc Một\" để tập trung vào {{ thông điệp }}.",
  "65a10d7c3f692": "Dùng khung Kim tự tháp ngược để tạo bài đăng mạng xã hội bắt đầu bằng {{ thông tin }} rồi chuyển sang {{ thông tin phụ }}, giúp người đọc nắm nhanh ý chính.",
  "65a10d7c3faa1": "Tạo bài đăng mạng xã hội quảng bá cho {{ sản phẩm/dịch vụ }}.",
  "65a10d7c3fed4": "Viết thông báo mạng xã hội về {{ sản phẩm/thay đổi/ra mắt }}.",
  "65a10d7c402ea": "Viết bài đăng mạng xã hội thu hút khách hàng tiềm năng cho {{ sản phẩm/dịch vụ }}.",
  "65a10d7c4071b": "Viết bài đăng mạng xã hội dẫn lưu lượng truy cập đến {{ trang web }}.",
  "65a10d7c40ae6": "Viết bài đăng mạng xã hội quảng bá {{ giảm giá/voucher/khuyến mãi }}.",
  "65a10d7c40ebd": "Tạo bài đăng mạng xã hội quảng bá bài viết về {{ chủ đề }}.",
  "65a10d7c4127e": "Viết bài đăng mạng xã hội quảng bá {{ loại sự kiện + ngày }}.",
  "65a10d7c41651": "Viết bài đăng mạng xã hội về {{ sản phẩm/dịch vụ }} và đề cập {{ nỗi đau của khách hàng }}.",
  "65a10d7c41a0b": "Mô tả tác động khi dùng {{ sản phẩm/tính năng }} với tư cách {{ nghề nghiệp/doanh nghiệp }}.",
  "65a10d7c41e03": "Viết 10 ý tưởng mở bài hấp dẫn cho bài đăng mạng xã hội về {{ chủ đề }}.",
  "65a10d7c42352": "Soạn bài đăng mạng xã hội cho {{ sản phẩm/dịch vụ }} chạm vào cảm xúc tích cực của khách hàng.",
  "65a10d7c4270f": "Hoàn thiện đoạn văn: Chúng tôi ra mắt {{ tên sản phẩm }} để giúp bạn {{ lợi ích }}.",
  "65a10d7c42a85": "Hoàn thiện đoạn văn: Chúng tôi ra mắt {{ tên sản phẩm }} để giúp bạn {{ lợi ích }}.",
  "65a10d7c42e51": "Tạo bài đăng làm nổi bật tính năng độc đáo của {{ sản phẩm }}.",
  "65a10d7c432c6": "Tạo bài đăng giới thiệu lợi ích khi dùng {{ tên sản phẩm }} cho {{ vấn đề }}.",
  "65a10d7c43790": "Xây dựng bài đăng quảng bá chương trình giảm giá có thời hạn cho {{ tên sản phẩm }}.",
  "65a10d7c43c9e": "Tạo bài đăng khuyến khích khách hàng để lại đánh giá cho {{ tên sản phẩm }}.",
  "65a10d7c44129": "Tạo bài đăng tạo cảm giác cấp bách mua {{ tên sản phẩm }}.",
  "65a10d7c44596": "Tạo bài đăng mạng xã hội so sánh {{ tên sản phẩm }} với sản phẩm tương tự trên thị trường.",
  "65a10d7c44981": "Xây dựng bài đăng mạng xã hội giới thiệu lời chứng thực của khách hàng về {{ tên sản phẩm }}.",
  "65a10d7c44e6a": "Tạo bài đăng mạng xã hội minh họa cách dùng {{ tên sản phẩm }} trong tình huống thực tế.",
  "65a10d7c4535d": "Tạo bài đăng mạng xã hội nhắm {{ đối tượng cụ thể }} và giải thích cách {{ tên sản phẩm }} giúp họ.",
  "65a10d7c45766": "Vẽ nên bức tranh cuộc sống của khách hàng sau khi dùng {{ sản phẩm/tính năng }}.",
  "65a10d7c45ba0": "Liệt kê các phản đối của khách hàng khi mua {{ sản phẩm/dịch vụ }}.",
  "65a10d7c4603c": "Lập danh sách lợi ích của {{ sản phẩm/dịch vụ }}.",
  "65a10d7c46905": "Viết đánh giá về {{ sản phẩm }} dựa trên thông tin sau:",
  "65a10d7c46d5d": "Viết đoạn văn về tính năng của {{ sản phẩm/dịch vụ }}.",
  "65a10d7c47114": "Viết đoạn văn mô tả {{ tên sản phẩm }} dựa trên các ý tưởng sau:",
  "65a10d7c475c1": "Tạo bài đăng mạng xã hội liệt kê lợi ích của {{ sản phẩm/dịch vụ }} cho {{ loại khách hàng }}.",
  "65a10d7c47af8": "Tạo bài hướng dẫn giải thích các bước dùng {{ sản phẩm/dịch vụ }} để đạt {{ mục tiêu hoặc kết quả cụ thể }}.",
  "65a10d7c4800f": "Tạo bài đăng mạng xã hội chia {{ chủ đề }} thành các bước dễ hiểu.",
  "65a10d7c484fa": "Tạo bài đăng mạng xã hội hướng dẫn và hỗ trợ người dùng gặp {{ vấn đề }} với {{ sản phẩm }}.",
  "65a10d7c48907": "Tạo bài hướng dẫn giải thích lợi ích và ưu điểm khi dùng {{ sản phẩm/dịch vụ }} so với giải pháp thay thế.",
  "65a10d7c48ca1": "Viết bài hướng dẫn từng bước khắc phục {{ lỗi }} liên quan {{ sản phẩm/dịch vụ }}.",
  "65a10d7c49150": "Tạo bài hướng dẫn thể hiện tính linh hoạt và khả năng thích ứng của {{ sản phẩm/dịch vụ }} với nhiều trường hợp sử dụng khác nhau.",
  "65a10d7c4964b": "Tạo bài hướng dẫn đưa lời khuyên dùng {{ sản phẩm/dịch vụ }} để nâng cao năng suất hoặc hiệu quả.",
  "65a10d7c49a44": "Tạo bài hướng dẫn giải thích khác biệt và sắc thái giữa các phiên bản hoặc gói {{ sản phẩm/dịch vụ }} khác nhau.",
  "65a10d7c49e2e": "Tạo bài đăng giới thiệu các tùy chọn tùy biến và cá nhân hóa cho {{ sản phẩm }}.",
  "65a10d7c4a217": "Tạo bài hướng dẫn từng bước cài đặt hoặc thiết lập {{ sản phẩm/dịch vụ }}.",
  "65a10d7c4a623": "Viết bài hướng dẫn thể hiện mức giá phải chăng và giá trị khi dùng {{ sản phẩm/dịch vụ }} so với giải pháp khác.",
  "65a10d7c4aa53": "Nhắm {{ chân dung khách hàng lý tưởng }} bằng {{ loại nội dung cụ thể }} có giá trị để khuyến khích họ {{ hành động mong muốn }}.",
  "65a10d7c4ae24": "Dùng bằng chứng xã hội và uy tín của {{ loại người ảnh hưởng }} để thuyết phục {{ chân dung khách hàng lý tưởng }} dùng thử {{ sản phẩm/dịch vụ }} và chia sẻ trải nghiệm tích cực với người theo dõi.",
  "65a10d7c4b1f6": "Giới thiệu tính năng và lợi ích độc đáo của {{ sản phẩm/dịch vụ }} theo cách sáng tạo, vui tươi với {{ loại nội dung cụ thể }} từ {{ loại người ảnh hưởng }}.",
  "65a10d7c4b67f": "Thu hút {{ chân dung khách hàng lý tưởng }} bằng {{ loại người ảnh hưởng }} gần gũi và thuyết phục họ thực hiện {{ hành động mong muốn }} với {{ sản phẩm/dịch vụ }} của bạn.",
  "65a10d7c4bbbf": "Tạo cảm giác cấp bách và sợ bỏ lỡ cho {{ chân dung khách hàng lý tưởng }} khi {{ loại người ảnh hưởng }} chia sẻ ưu đãi và khuyến mãi độc quyền cho {{ sản phẩm/dịch vụ }}.",
  "65a10d7c4c020": "Tạo bài hướng dẫn giải thích quy trình nâng cấp hoặc hạ cấp gói đăng ký {{ sản phẩm/dịch vụ }}.",
  "65a10d7c4c4b1": "Tạo nội dung quảng cáo mạng xã hội làm nổi bật {{ giảm giá/khuyến mãi }}. Dùng cụm từ tạo cảm giác cấp bách để khuyến khích khách mua ngay.",
  "65a10d7c4c969": "Viết quảng cáo mạng xã hội giới thiệu {{ sản phẩm/dịch vụ mới }} cho khách hàng. Dùng ngôn ngữ nhấn mạnh tính năng và lợi ích độc đáo, tạo không khí hào hứng cho đợt ra mắt.",
  "65a10d7c4cdc3": "Tạo quảng cáo mạng xã hội thu hút khách hàng tiềm năng cho {{ sản phẩm/dịch vụ }}. Dùng ngôn ngữ nhắm {{ khách hàng lý tưởng }} và làm nổi bật lợi ích mà {{ sản phẩm/dịch vụ }} mang lại.",
  "65a10d7c4d1d6": "Viết quảng cáo mạng xã hội dẫn lưu lượng truy cập đến {{ trang web }}. Dùng ngôn ngữ gợi tò mò và khuyến khích khách bấm vào để tìm hiểu thêm.",
  "65a10d7c4d5dc": "Viết quảng cáo mạng xã hội giải quyết {{ nỗi đau của khách hàng }} và quảng bá giải pháp là {{ sản phẩm/dịch vụ }}. Dùng ngôn ngữ đồng cảm với nhu cầu khách hàng và định vị sản phẩm hoặc dịch vụ là giải pháp họ đang tìm kiếm.",
  "65a10d7c4d9c6": "Tạo quảng cáo mạng xã hội làm nổi bật tác động khi dùng {{ sản phẩm/dịch vụ }} trong {{ nghề nghiệp }}. Dùng ngôn ngữ nhấn mạnh lợi ích và cách sản phẩm hoặc tính năng hỗ trợ.",
  "65a10d7c4ddaf": "Tạo quảng cáo mạng xã hội từ mô tả sản phẩm/dịch vụ sau:",
  "65a10d7c4e191": "Tạo nội dung quảng cáo mạng xã hội quảng bá {{ ưu đãi có thời hạn }}. Dùng ngôn ngữ tạo cảm giác cấp bách và khuyến khích khách hành động nhanh.",
  "65a10d7c4e5e4": "Viết nội dung quảng cáo thu hút {{ chân dung khách hàng lý tưởng }} của tôi và khuyến khích họ mua {{ sản phẩm/dịch vụ }}, từ đó tăng lưu lượng truy cập và doanh số.",
  "65a10d7c4e9fc": "Tạo nội dung quảng cáo tạo cảm giác cấp bách và sợ bỏ lỡ ở {{ chân dung khách hàng lý tưởng }} của tôi bằng cách làm nổi bật ưu đãi và khuyến mãi độc quyền cho {{ sản phẩm/dịch vụ }}.",
  "65a10d7c4edd3": "Tạo nội dung quảng cáo tận dụng sự chân thật và gần gũi của {{ thương hiệu/công ty }} để kết nối với {{ chân dung khách hàng lý tưởng }} và thuyết phục họ thực hiện {{ hành động mong muốn }} với {{ sản phẩm/dịch vụ }}.",
  "65a10d7c4f1c3": "Tạo nội dung quảng cáo khai thác bằng chứng xã hội và uy tín của {{ thương hiệu/công ty }} để thuyết phục {{ chân dung khách hàng lý tưởng }} dùng thử {{ sản phẩm/dịch vụ }} và chia sẻ trải nghiệm tích cực với người theo dõi.",
  "65a10d7c4f5e1": "Viết nội dung quảng cáo làm nổi bật thẩm quyền và chuyên môn của {{ thương hiệu/công ty }} để giáo dục {{ chân dung khách hàng lý tưởng }} về lợi ích {{ sản phẩm/dịch vụ }} và thuyết phục họ mua hàng.",
  "65a10d7c4f9dd": "Tạo nội dung quảng cáo hé lộ sản phẩm hoặc dịch vụ sắp ra mắt để tạo cảm giác mong đợi và hào hứng ở {{ chân dung khách hàng lý tưởng }}. Nội dung quảng cáo cần có lời kêu gọi hành động rõ ràng và thuyết phục.",
  "65a10d7c4fdf8": "Tạo nội dung quảng cáo thể hiện trải nghiệm cá nhân, độc đáo của {{ chân dung khách hàng lý tưởng }} với {{ sản phẩm/dịch vụ }} và khuyến khích họ chia sẻ đánh giá tích cực với người theo dõi.",
  "65a10d7c50248": "Tạo quảng cáo mạng xã hội có lời chứng thực của khách hàng. Dùng ngôn ngữ nhấn mạnh trải nghiệm tích cực của khách và khuyến khích người khác dùng thử sản phẩm hoặc dịch vụ.",
  "65a10d7c50695": "Viết quảng cáo mạng xã hội quảng bá {{ sự kiện sắp tới }}. Dùng ngôn ngữ tạo hào hứng và khuyến khích khách đăng ký hoặc tham dự.",
  "65a10d7c50afe": "Tạo quảng cáo mạng xã hội quảng bá {{ dùng thử miễn phí }} cho {{ sản phẩm hoặc dịch vụ }}. Dùng ngôn ngữ nhấn mạnh lợi ích và khuyến khích khách trải nghiệm.",
  "65a10d7c50f15": "Viết quảng cáo mạng xã hội quảng bá {{ khuyến mãi theo mùa }}. Dùng ngôn ngữ gắn khuyến mãi với mùa và tạo cảm giác hào hứng.",
  "65a10d7c512b9": "Tạo quảng cáo mạng xã hội quảng bá chương trình giới thiệu bạn bè. Dùng ngôn ngữ nhấn mạnh lợi ích và khuyến khích khách giới thiệu bạn bè.",
  "65a10d7c5166c": "Viết quảng cáo mạng xã hội quảng bá {{ nâng cấp }}. Dùng ngôn ngữ làm nổi bật giá trị của gói nâng cấp và khuyến khích khách cập nhật gói.",
  "65a10d7c51a58": "Tạo quảng cáo mạng xã hội quảng bá đặt trước {{ sản phẩm/dịch vụ }}. Dùng ngôn ngữ tạo hào hứng và khuyến khích khách là người đầu tiên sở hữu.",
  "65a10d7c51e29": "Tạo bài đăng mạng xã hội chúc mừng sinh nhật nhân viên.",
  "65a10d7c52201": "Tạo bài đăng mạng xã hội củng cố {{ sứ mệnh/giá trị }} sau:",
  "65a10d7c5265e": "Viết bài đăng mạng xã hội giới thiệu thành viên mới trong đội ngũ.",
  "65a10d7c52a19": "Tạo bài đăng mạng xã hội cảm ơn khách hàng trung thành.",
  "65a10d7c52ddf": "Viết bài đăng mạng xã hội kỷ niệm {{ cột mốc }} liên quan {{ tên công ty }}.",
  "65a10d7c531a2": "Tạo bài đăng mạng xã hội quảng bá sự kiện tài trợ cho {{ loại hoạt động }}.",
  "65a10d7c535dd": "Viết bài đăng mạng xã hội chia sẻ sự thật thú vị hoặc câu đố về {{ ngành }}.",
  "65a10d7c53a3f": "Tạo bài đăng mạng xã hội ghi nhận và chúc mừng {{ thành tựu }} của {{ vai trò và tên nhân viên }}.",
  "65a10d7c53f48": "Viết bài đăng mạng xã hội khuyến khích người theo dõi chia sẻ trải nghiệm với sản phẩm hoặc dịch vụ của {{ tên công ty của bạn }}.",
  "65a10d7c543ed": "Tạo bài đăng mạng xã hội ghi nhận và cảm ơn đối tác hoặc nhà cung cấp đã giúp bạn đạt mục tiêu.",
  "65a10d7c547f9": "Viết bài đăng mạng xã hội thể hiện sự sáng tạo và đổi mới của nhân viên tại {{ tên công ty }} qua {{ dự án }}.",
  "65a10d7c54bcf": "Tạo bài đăng mạng xã hội giới thiệu đánh giá hoặc phản hồi tích cực từ khách hàng về {{ sản phẩm/dịch vụ/sự kiện }}.",
  "65a10d7c54fb4": "Viết bài đăng mạng xã hội ghi nhận và trân trọng sự chăm chỉ, cống hiến của nhân viên tại {{ tên công ty }}.",
  "65a10d7c553ce": "Viết bài đăng mạng xã hội nói về {{ thành viên nhóm }} và làm nổi bật đóng góp của họ cho công ty trong {{ phòng ban }}.",
  "65a10d7c564ef": "Tạo chú thích cho video mạng xã hội đưa người theo dõi vào hậu trường quá trình tạo {{ sự kiện/sản phẩm }}.",
  "65a10d7c5748a": "Viết bài đăng mạng xã hội thông báo buổi hỏi đáp trực tiếp với thành viên chuyên về {{ vai trò }}, nơi người theo dõi có thể đặt câu hỏi về vai trò của họ.",
  "65a10d7c58537": "Tạo bài đăng mạng xã hội về một ngày làm việc của {{ nghề nghiệp }}, thể hiện thói quen và trách nhiệm hàng ngày.",
  "65a10d7c5961a": "Tạo bài đăng mạng xã hội thể hiện cam kết bền vững và thân thiện môi trường của công ty trong hoạt động và sản phẩm.",
  "65a10d7c59b85": "Viết bài đăng mạng xã hội thể hiện cam kết phát triển và đào tạo nhân viên của công ty.",
  "65a10d7c5a01d": "Viết lời kêu gọi hành động cho {{ sản phẩm }} để người đọc {{ hành động }}.",
  "65a10d7c5a4a1": "Viết lời kêu gọi hành động cho {{ sản phẩm/dịch vụ }}.",
  "65a10d7c5a945": "Viết lời kêu gọi hành động cho nội dung sau:",
  "65a10d7c5ad5c": "Viết lời kêu gọi hành động quảng bá {{ sản phẩm/dịch vụ }} cho {{ loại khách hàng }}.",
  "65a10d7c5b11a": "Tạo lời kêu gọi hành động cho {{ sản phẩm/dịch vụ }} và bao gồm cụm từ sau:",
  "65a10d7c5b52a": "Đưa ra 10 lời kêu gọi hành động mạnh mẽ về {{ sản phẩm/dịch vụ }}.",
  "65a10d7c5b95d": "Viết bài đăng mạng xã hội dựa trên thống kê về cà phê {{ chủ đề }}.",
  "65a10d7c5bdc1": "Viết bài đăng mạng xã hội thảo luận huyền thoại về {{ chủ đề }}.",
  "65a10d7c5c225": "Tạo bài đăng mạng xã hội nói về những điều không nên làm với {{ chủ đề }}.",
  "65a10d7c5c6f7": "Tạo bài đăng mạng xã hội về mẹo/lợi ích của {{ chủ đề }}.",
  "65a10d7c5cc0a": "Viết bài đánh giá mạng xã hội về {{ sản phẩm }}.",
  "65a10d7c5d02e": "Tạo bài đăng mạng xã hội về lịch sử của {{ chủ đề }}.",
  "65a10d7c5d468": "Liệt kê thách thức đi kèm {{ nghề nghiệp }} để đăng trên {{ nền tảng mạng xã hội }} cho {{ đối tượng }}.",
  "65a10d7c5d8b0": "Viết bài đăng mạng xã hội so sánh {{ chủ đề }} và {{ chủ đề }}.",
  "65a10d7c5dccd": "Tạo danh sách ưu và nhược điểm của {{ chủ đề }}.",
  "65a10d7c5e119": "Mời đối tượng chia sẻ suy nghĩ hoặc trải nghiệm liên quan {{ chủ đề }}, và khuyến khích thảo luận trong phần bình luận.",
  "65a10d7c5e582": "Chia sẻ sự thật bất ngờ hoặc ít ai biết về {{ chủ đề }}.",
  "65a10d7c5ea7f": "Giải thích vì sao {{ sản phẩm }} ngày càng quan trọng trong {{ lĩnh vực }}, và cách nó giúp cải thiện {{ kết quả }}.",
  "65a10d7c5eee4": "Thảo luận lợi ích và hạn chế tiềm năng của {{ phương pháp/công cụ }}, cân nhắc ưu nhược điểm.",
  "65a10d7c5f32d": "Đưa ví dụ thực tế hoặc tình huống thực tế về cách {{ phương pháp/công cụ }} được áp dụng trong {{ ngành }} và tác động đến {{ nhóm đối tượng }}.",
  "65a10d7c5f6de": "Giải thích rõ ràng, ngắn gọn cách một {{ sản phẩm }} hoạt động, dùng ngôn ngữ đơn giản và ví dụ minh họa.",
  "65a10d7c5fb79": "Giải đáp hiểu lầm hoặc câu hỏi phổ biến liên quan {{ chủ đề }}, và làm rõ.",
  "65a10d7c5ff9f": "Dùng định dạng \"Câu hỏi thường gặp\" để trả lời câu hỏi phổ biến về {{ chủ đề }}, kèm giải thích hoặc tóm tắt ngắn gọn.",
  "65a10d7c60450": "Đặt câu hỏi gợi suy nghĩ hoặc thách thức liên quan {{ chủ đề }}, và khuyến khích đối tượng chia sẻ suy nghĩ hoặc quan điểm.",
  "65a10d7c608cf": "Đưa lời khuyên hoặc hướng dẫn cách {{ hành động }}, đồng thời giải quyết thách thức hoặc lo ngại phổ biến.",
  "65a10d7c60fa1": "Giải quyết huyền thoại hoặc hiểu lầm phổ biến liên quan {{ chủ đề }}, kèm bằng chứng hoặc ví dụ để bác bỏ.",
  "65a10d7c61455": "Giải thích vì sao {{ hiểu lầm }} gây hại hoặc dẫn lối, và cách nó ảnh hưởng nhận thức hoặc quyết định liên quan {{ hành động }}.",
  "65a10d7c6187e": "Tạo bài đăng mạng xã hội đưa ra luận điểm phản bác cho phát biểu sau:",
  "65a10d7c61c72": "Viết bài đăng mạng xã hội so sánh {{ chủ đề }} và {{ chủ đề }}.",
  "65a10d7c62102": "So sánh và đối chiếu {{ chủ đề }} và {{ chủ đề }}.",
  "65a10d7c6254e": "So sánh ưu và nhược điểm của {{ sản phẩm/dịch vụ/phương pháp }}.",
  "65a10d7c62913": "Tạo bài đăng mạng xã hội đưa ra ba luận điểm ủng hộ cho phát biểu sau:",
  "65a10d7c62c9d": "Tạo bài đăng mạng xã hội đưa ra luận điểm phản bác cho bài viết về {{ chủ đề }}.",
  "65a10d7c630b2": "Phân tích phê phán {{ chủ đề }}.",
  "65a10d7c63535": "Tạo bài đăng mạng xã hội như câu trả lời hay cho {{ phản đối của khách hàng }}.",
  "65a10d7c639f4": "Viết câu đùa hài hước về {{ chủ đề }}.",
  "65a10d7c63e57": "Nêu một sự thật thú vị về {{ chủ đề }} và tạo bài đăng mạng xã hội về nó.",
  "65a10d7c642c1": "Viết phép so sánh để giải thích {{ chủ đề }}.",
  "65a10d7c64766": "Viết bài đăng mạng xã hội hài hước về {{ chủ đề }}.",
  "65a10d7c64b3a": "Viết câu đố về {{ chủ đề }}.",
  "65a10d7c64f65": "Tạo thử thách mạng xã hội khuyến khích mọi người {{ hoạt động }}.",
  "65a10d7c6533b": "Nghĩ ra các câu chơi chữ dí dỏm về {{ chủ đề }}.",
  "65a10d7c6579e": "Tạo bài đăng mạng xã hội gợi ý {{ sách/phim/bản tin âm thanh/sản phẩm/dịch vụ }} cho {{ nhu cầu }}.",
  "65a10d7c65bb5": "Viết bài đăng mạng xã hội hài hước chọc vào {{ quan niệm sai lầm }}.",
  "65a10d7c660bb": "Tạo bài đăng mạng xã hội kể một giai thoại hoặc câu chuyện hài hước liên quan {{ ngành }}.",
  "65a10d7c66603": "Tạo bài đăng mạng xã hội làm nổi bật câu chơi chữ hài hước liên quan {{ sản phẩm/dịch vụ/ngành }}.",
  "65a10d7c66a55": "Tạo loạt bài đăng mạng xã hội với câu đùa hoặc ảnh chế hài hước về thách thức hoặc điều thú vị khi làm việc từ xa.",
  "65a10d7c66e69": "Viết bài đăng mạng xã hội xin lời khuyên hoặc ý kiến về {{ chủ đề }}.",
  "65a10d7c6727f": "Tạo bài đăng mạng xã hội mời người theo dõi chia sẻ ảnh chế yêu thích.",
  "65a10d7c676d7": "Viết bài đăng mạng xã hội mời người theo dõi chia sẻ câu đùa hoặc ảnh chế yêu thích về {{ chủ đề }}.",
  "65a10d7c67ad1": "Tạo bài đăng mạng xã hội mời người theo dõi chia sẻ câu nói yêu thích về {{ chủ đề }}.",
  "65a10d7c67f64": "Tạo bài đăng mạng xã hội mời người theo dõi chia sẻ ý kiến về {{ chủ đề }}.",
  "65a10d7c68484": "Khởi động cuộc tranh luận trên mạng xã hội về {{ chủ đề }}.",
  "65a10d7c6893b": "Viết bài đăng mạng xã hội đặt câu hỏi về {{ chủ đề }}",
  "65a10d7c68d38": "Tạo bài đăng mạng xã hội xin gợi ý {{ phim/sách/bản tin âm thanh }}.",
  "65a10d7c690ed": "Liệt kê 10 ý tưởng cuộc thi trên mạng xã hội.",
  "65a10d7c694b4": "Tạo bài đăng tặng quà trên mạng xã hội cho {{ sản phẩm/dịch vụ }}.",
  "65a10d7c69912": "Tạo khảo sát/trắc nghiệm mạng xã hội về {{ chủ đề }}.",
  "65a10d7c69d8d": "Tạo bài đăng mạng xã hội thông báo buổi hỏi đáp trực tiếp về {{ chủ đề }}.",
  "65a10d7c6a229": "Tạo 10 lựa chọn khảo sát cho trắc nghiệm về {{ chủ đề }}.",
  "65a10d7c6a6a0": "Tạo trắc nghiệm gợi ý sản phẩm giúp khách hàng tìm {{ sản phẩm }} phù hợp với {{ nhu cầu của họ }}. Dùng câu hỏi thu hẹp lựa chọn và làm nổi bật lợi ích từng sản phẩm.",
  "65a10d7c6abdc": "Tạo trắc nghiệm kiến thức về {{ chủ đề }}. Dùng câu hỏi thách thức khách hàng suy nghĩ và tìm hiểu thêm về chủ đề.",
  "65a10d7c6b03d": "Tạo trắc nghiệm đố vui về {{ ngành }}. Dùng câu hỏi kiểm tra kiến thức khách hàng và tạo trải nghiệm vui, tương tác.",
  "65a10d7c6b40f": "Tạo trắc nghiệm định hướng nghề nghiệp giúp khách hàng xác định con đường sự nghiệp lý tưởng. Dùng câu hỏi giới thiệu các vai trò và ngành khác nhau, kèm tài nguyên hữu ích để khám phá thêm.",
  "65a10d7c6b7f3": "Tạo trắc nghiệm du lịch giúp khách hàng tìm điểm đến lý tưởng. Dùng câu hỏi thể hiện sở thích du lịch khác nhau và cung cấp mẹo, tài nguyên hữu ích.",
  "65a10d7c6bc46": "Tạo trắc nghiệm ẩm thực giúp khách hàng xác định khẩu vị và khám phá công thức, nguyên liệu mới. Dùng câu hỏi giới thiệu các ẩm thực và hương vị khác nhau.",
  "65a10d7c6c0a5": "Tạo trắc nghiệm thời trang giúp khách hàng xác định phong cách cá nhân và tìm trang phục phù hợp. Dùng câu hỏi giới thiệu các phong cách thời trang khác nhau, kèm tài nguyên và lời khuyên hữu ích.",
  "65a10d7c6c493": "Tạo trắc nghiệm giáo dục giúp mọi người xác định phong cách học và tìm tài nguyên, mẹo học tập hữu ích. Dùng câu hỏi giới thiệu kỹ thuật học khác nhau và đưa mẹo, tài nguyên có thể áp dụng ngay.",
  "65a10d7c6c87d": "Tạo trắc nghiệm âm nhạc giúp khách hàng xác định thể loại và nghệ sĩ yêu thích. Dùng câu hỏi giới thiệu các phong cách âm nhạc khác nhau, kèm tài nguyên và đố vui.",
  "65a10d7c6cd01": "Tạo trắc nghiệm phim và truyền hình giúp khách hàng xác định phim và chương trình yêu thích. Dùng câu hỏi giới thiệu các thể loại khác nhau, kèm tài nguyên và đố vui.",
  "65a10d7c6d1bd": "Tạo cuộc thi ảnh khuyến khích khách hàng chia sẻ ảnh khi dùng {{ sản phẩm }}. Dùng thẻ gắn thẻ riêng để theo dõi bài dự thi và trao giải cho ảnh hay nhất.",
  "65a10d7c6e33b": "Tạo cuộc thi chú thích khuyến khích khách hàng viết chú thích hài hước hoặc sáng tạo cho ảnh liên quan {{ chủ đề }}. Trao giải cho chú thích hay nhất.",
  "65a10d7c6f3ba": "Tạo cuộc xổ số khuyến khích khách hàng tham gia để có cơ hội trúng {{ giải thưởng }}.",
  "65a10d7c6f79c": "Tạo cuộc thi đố vui về {{ chủ đề }}. Dùng loạt câu hỏi thách thức kiến thức khách hàng và trao giải cho điểm cao nhất.",
  "65a10d7c6fc2b": "Tạo cuộc thi nội dung do người dùng tạo khuyến khích khách hàng sáng tạo và chia sẻ nội dung liên quan {{ chủ đề }}. Dùng thẻ gắn thẻ riêng để theo dõi bài dự thi và trao giải cho nội dung hay nhất.",
  "65a10d7c70137": "Tạo cuộc thi sáng tác khuyến khích khách hàng viết truyện ngắn, thơ hoặc tác phẩm sáng tạo khác liên quan {{ chủ đề }}. Dùng thẻ gắn thẻ riêng để theo dõi bài dự thi và trao giải cho tác phẩm hay nhất.",
  "65a10d7c705df": "Tạo cuộc thi giải nghĩa biểu tượng cảm xúc khuyến khích khách hàng giải thích loạt biểu tượng cảm xúc liên quan {{ chủ đề }}. Dùng thẻ gắn thẻ riêng để theo dõi bài dự thi và trao giải cho cách giải thích sáng tạo nhất.",
  "65a10d7c70a28": "Tạo cuộc thi thiết kế lại biểu trưng khuyến khích khách hàng thiết kế lại biểu trưng thương hiệu. Dùng thẻ gắn thẻ riêng để theo dõi bài dự thi và trao giải cho thiết kế hay nhất.",
  "65a10d7c70e13": "Tạo cuộc thi \"Đặt tên sản phẩm\" khuyến khích khách hàng nghĩ tên sáng tạo cho {{ sản phẩm/dịch vụ }}.",
  "65a10d7c71266": "Viết thông điệp truyền cảm hứng trên mạng xã hội cho {{ đối tượng mục tiêu }}.",
  "65a10d7c71650": "Tạo bài đăng mạng xã hội chia sẻ câu nói truyền cảm hứng về {{ chủ đề }}.",
  "65a10d7c71ae7": "Tạo bài đăng chia sẻ câu chuyện thành công truyền cảm hứng về {{ chủ đề }}.",
  "65a10d7c71f95": "Viết bài đăng mạng xã hội truyền cảm hứng về cách vượt qua {{ thử thách }}.",
  "65a10d7c724b2": "Tạo bài đăng mạng xã hội chia sẻ thông điệp truyền động lực cho người theo dõi là doanh nhân hoặc chủ doanh nghiệp.",
  "65a10d7c7296b": "Chia sẻ câu chuyện về người vượt qua nghịch cảnh và thành công trong lĩnh vực của họ.",
  "65a10d7c72dcd": "Viết bài truyền cảm hứng về việc chấp nhận rủi ro và bước ra khỏi vùng an toàn.",
  "65a10d7c73248": "Tạo bài đăng mạng xã hội khuyến khích người theo dõi không bỏ cuộc với ước mơ của mình.",
  "65a10d7c73645": "Tạo bài đăng chia sẻ mẹo giữ động lực và tập trung trong thời điểm khó khăn.",
  "65a10d7c73ae9": "Viết thông điệp truyền cảm hứng về sức mạnh của kiên trì và quyết tâm khi theo đuổi mục tiêu.",
  "65a10d7c74012": "Chia sẻ câu chuyện cá nhân về việc vượt qua trở ngại và cách điều đó giúp bạn mạnh mẽ hơn.",
  "65a10d7c74459": "Tạo bài đăng về tầm quan trọng của chăm sóc bản thân khi theo đuổi mục tiêu.",
  "65a10d7c74856": "Tạo bài đăng mạng xã hội về lợi ích của suy nghĩ tích cực và tư duy phát triển.",
  "65a10d7c74c34": "Viết thông điệp truyền cảm hứng về sức mạnh của cộng đồng và sự hỗ trợ mà cộng đồng mang lại.",
  "65a10d7c7508e": "Chia sẻ câu chuyện về người tạo tác động tích cực cho thế giới và truyền cảm hứng cho người khác làm điều tương tự.",
  "65a10d7c75461": "Tạo bài đăng mạng xã hội về giá trị của sự chăm chỉ và kiên trì trên con đường thành công.",
  "65a10d7c75842": "Viết thông điệp truyền cảm hứng về tầm quan trọng của việc đặt mục tiêu và nỗ lực theo đuổi.",
  "65a10d7c75c4e": "Tạo bài đăng chia sẻ mẹo giữ tập trung và năng suất khi làm việc tại nhà.",
  "65a10d7c760cd": "Chia sẻ câu chuyện truyền động lực về người theo đuổi đam mê và tìm thấy thành công.",
  "65a10d7c76496": "Tạo bài đăng mạng xã hội về lợi ích của việc đón nhận thử thách mới và học kỹ năng mới.",
  "65a10d7c76908": "Viết thông điệp truyền cảm hứng về sức mạnh của lòng biết ơn và trân trọng những điều nhỏ trong cuộc sống.",
  "65a10d7c76dca": "Tạo bài đăng chia sẻ trải nghiệm cá nhân vượt qua tình huống khó khăn và bài học rút ra.",
  "65a10d7c772f6": "Chia sẻ câu chuyện về người biến thất bại thành cơ hội phát triển và thành công.",
  "65a10d7c7779b": "Tạo bài đăng mạng xã hội về tầm quan trọng của tự phản tư và tự hoàn thiện.",
};

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, `${JSON.stringify(viMap, null, 2)}\n`, 'utf8');
console.log(`Wrote ${Object.keys(viMap).length} entries to ${outPath}`);
